### ISSUE TITLE
wechaty 启动 rx-queue 依赖报错

### ISSUE THREAD

**Issue by 3014zhangshuo** [botorange/wechaty-puppet-padpro#103]
> 重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

## 0. 发 Issue 指南

1. 请运行下面的命令，看问题是否可以被解决：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```
2. 请在 [FAQ 清单](https://docs.chatie.io/v/zh/faq) 看是否已有解决办法。

3. 请先在issue 中搜关键信息，确认你要发的内容和之前的issue 不重复。

## 1. 提供你的包版本信息
- wechaty 版本：0.22.6
- wechaty-puppet-padpro 版本：0.0.54
- node 版本：v8.4.0
- 你使用的操作系统：mac, Ubuntu 16.04.2 LTS

## 2. Bug 描述
docker container 直接运行出现报错

## 3. 复现的步骤 (或者解决的步骤)

sudo docker run -d -t -i --rm --name=wechat-box -e WECHATY_PUPPET_PADPRO_TOKEN="xxx" xx/wechat-file:latest

## 4. 期待程序运行的结果
请用精简的语言描述你期待运行的结果

## 5. 程序实际运行的结果
请用精简的语言或者截图描述实际运行的结果（**请不要在这里粘贴日志截图**）

## 6. 完整的日志信息：
通过`WECHATY_LOG=silly`设定环境变量，将设置log 等级为 silly，获取最详细的日志信息（默认log 等级为 info）
**请提供完整的日志信息(不要只提供部分的日志截图，请复制粘贴日志内容！)**
<details>
<summary>
03:22:23 INFO PuppetManager install(wechaty-puppet-padpro@latest) done
03:22:24 VERB Puppet constructor({"timeout":240}) #0
03:22:24 VERB StateSwitch constructor(name=PuppetPadpro)
03:22:24 VERB MemoryCard constructor(undefined)
03:22:24 VERB MemoryCard getStorage() for storage type: N/A
03:22:24 VERB MemoryCard load() from storage: N/A
03:22:24 VERB MemoryCard load() no storage
03:22:24 VERB Puppet constructor() watchdog timeout set to 240 seconds
03:22:24 VERB HotImport callerResolve(., /bot/node_modules/wechaty-puppet/dist/src/puppet.js)
03:22:24 SILL HotImport callerResolve() callsites() file=/bot/node_modules/hot-import/dist/src/hot-import.js, type=Object
03:22:24 SILL HotImport callerResolve() callsites() file=/bot/node_modules/wechaty-puppet/dist/src/puppet.js, type=null
03:22:24 SILL HotImport callerResolve() callsites() file=/bot/node_modules/wechaty/node_modules/wechaty-puppet-padpro/dist/src/puppet-padpro.js, type=null
03:22:24 SILL HotImport callerResolve() callerFile=/bot/node_modules/wechaty/node_modules/wechaty-puppet-padpro/dist/src/puppet-padpro.js
03:22:24 VERB Puppet constructor() childClassPath=/bot/node_modules/wechaty/node_modules/wechaty-puppet-padpro/dist/src
03:22:24 VERB Puppet constructor() memory.load() done
03:22:24 VERB Puppet setMemory()
03:22:24 VERB Wechaty initPuppetEventBridge(Puppet#0<PuppetPadpro>()/PuppetPadpro#0)
03:22:24 VERB Wechaty initPuppetEventBridge() puppet.on(friendship) registered
03:22:24 VERB Wechaty initPuppetEventBridge() puppet.on(login) registered
03:22:24 VERB Wechaty initPuppetEventBridge() puppet.on(logout) registered
03:22:24 VERB Wechaty initPuppetEventBridge() puppet.on(message) registered
03:22:24 VERB Wechaty initPuppetEventBridge() puppet.on(room-invite) registered
03:22:24 VERB Wechaty initPuppetEventBridge() puppet.on(room-join) registered
03:22:24 VERB Wechaty initPuppetEventBridge() puppet.on(room-leave) registered
03:22:24 VERB Wechaty initPuppetEventBridge() puppet.on(room-topic) registered
03:22:24 VERB Wechaty initPuppetEventBridge() puppet.on(scan) registered
03:22:24 VERB Wechaty initPuppetEventBridge() puppet.on(dong) registered
03:22:24 VERB Wechaty initPuppetEventBridge() puppet.on(error) registered
03:22:24 VERB Wechaty initPuppetEventBridge() puppet.on(ready) registered
03:22:24 VERB Wechaty initPuppetEventBridge() puppet.on(reset) registered
03:22:24 VERB Wechaty initPuppetEventBridge() puppet.on(watchdog) registered
03:22:24 VERB Wechaty initAccessory(Puppet#0<PuppetPadpro>()/PuppetPadpro#0)
03:22:24 SILL Accessory <Contact> static set wechaty = "Wechaty#cjuhsi6p300001muw8tz8tewm<wechaty-puppet-padpro>()"
03:22:24 SILL Accessory <ContactSelf> static set wechaty = "Wechaty#cjuhsi6p300001muw8tz8tewm<wechaty-puppet-padpro>()"
03:22:24 SILL Accessory <Friendship> static set wechaty = "Wechaty#cjuhsi6p300001muw8tz8tewm<wechaty-puppet-padpro>()"
03:22:24 SILL Accessory <Message> static set wechaty = "Wechaty#cjuhsi6p300001muw8tz8tewm<wechaty-puppet-padpro>()"
03:22:24 SILL Accessory <Room> static set wechaty = "Wechaty#cjuhsi6p300001muw8tz8tewm<wechaty-puppet-padpro>()"
03:22:24 SILL Accessory <RoomInvitation> static set wechaty = "Wechaty#cjuhsi6p300001muw8tz8tewm<wechaty-puppet-padpro>()"
03:22:24 SILL Accessory <Contact> static set puppet = "Puppet#0<PuppetPadpro>()/PuppetPadpro#0"
03:22:24 SILL Accessory <ContactSelf> static set puppet = "Puppet#0<PuppetPadpro>()/PuppetPadpro#0"
03:22:24 SILL Accessory <Friendship> static set puppet = "Puppet#0<PuppetPadpro>()/PuppetPadpro#0"
03:22:24 SILL Accessory <Message> static set puppet = "Puppet#0<PuppetPadpro>()/PuppetPadpro#0"
03:22:24 SILL Accessory <Room> static set puppet = "Puppet#0<PuppetPadpro>()/PuppetPadpro#0"
03:22:24 SILL Accessory <RoomInvitation> static set puppet = "Puppet#0<PuppetPadpro>()/PuppetPadpro#0"
03:22:24 SILL Accessory <Wechaty> set puppet = "Puppet#0<PuppetPadpro>()/PuppetPadpro#0"
03:22:24 SILL StateSwitch <PuppetPadpro> on() is false
03:22:24 SILL StateSwitch <PuppetPadpro> on() is false
03:22:24 VERB StateSwitch <PuppetPadpro> on(pending) <- (false)
03:22:24 INFO WechatGateway init(puppet_padpro_2d85d172d6d3c5e1, padpro.botorange.com:6666, undefined)
TypeError: rx_queue_1.DelayQueueExecutor is not a constructor
    at new DedupeApi (/bot/node_modules/wechaty/node_modules/wechaty-puppet-padpro/dist/src/gateway/dedupe-api.js:33:25)
    at new WechatGateway (/bot/node_modules/wechaty/node_modules/wechaty-puppet-padpro/dist/src/gateway/wechat-gateway.js:56:26)
    at Function.init (/bot/node_modules/wechaty/node_modules/wechaty-puppet-padpro/dist/src/gateway/wechat-gateway.js:28:26)
    at PuppetPadpro.<anonymous> (/bot/node_modules/wechaty/node_modules/wechaty-puppet-padpro/dist/src/puppet-padpro.js:114:50)
    at Generator.next (<anonymous>)
    at /bot/node_modules/wechaty/node_modules/wechaty-puppet-padpro/dist/src/puppet-padpro.js:25:71
    at new Promise (<anonymous>)
    at __awaiter (/bot/node_modules/wechaty/node_modules/wechaty-puppet-padpro/dist/src/puppet-padpro.js:21:12)
    at PuppetPadpro.start (/bot/node_modules/wechaty/node_modules/wechaty-puppet-padpro/dist/src/puppet-padpro.js:101:16)
    at Wechaty.<anonymous> (/bot/node_modules/wechaty/dist/src/wechaty.js:616:35)
    at Generator.next (<anonymous>)
    at fulfilled (/bot/node_modules/wechaty/dist/src/wechaty.js:4:58)
03:22:24 ERR Wechaty start() exception: rx_queue_1.DelayQueueExecutor is not a constructor
03:22:24 ERR Config ###########################
03:22:24 ERR Config unhandledRejection: TypeError: rx_queue_1.DelayQueueExecutor is not a constructor [object Promise]
03:22:24 ERR Config ###########################
03:22:24 ERR Config process.on(unhandledRejection) promise.catch(rx_queue_1.DelayQueueExecutor is not a constructor)
Config TypeError: rx_queue_1.DelayQueueExecutor is not a constructor
    at new DedupeApi (/bot/node_modules/wechaty/node_modules/wechaty-puppet-padpro/dist/src/gateway/dedupe-api.js:33:25)
    at new WechatGateway (/bot/node_modules/wechaty/node_modules/wechaty-puppet-padpro/dist/src/gateway/wechat-gateway.js:56:26)
    at Function.init (/bot/node_modules/wechaty/node_modules/wechaty-puppet-padpro/dist/src/gateway/wechat-gateway.js:28:26)
    at PuppetPadpro.<anonymous> (/bot/node_modules/wechaty/node_modules/wechaty-puppet-padpro/dist/src/puppet-padpro.js:114:50)
    at Generator.next (<anonymous>)
    at /bot/node_modules/wechaty/node_modules/wechaty-puppet-padpro/dist/src/puppet-padpro.js:25:71
    at new Promise (<anonymous>)
    at __awaiter (/bot/node_modules/wechaty/node_modules/wechaty-puppet-padpro/dist/src/puppet-padpro.js:21:12)
    at PuppetPadpro.start (/bot/node_modules/wechaty/node_modules/wechaty-puppet-padpro/dist/src/puppet-padpro.js:101:16)
    at Wechaty.<anonymous> (/bot/node_modules/wechaty/dist/src/wechaty.js:616:35)
    at Generator.next (<anonymous>)
    at fulfilled (/bot/node_modules/wechaty/dist/src/wechaty.js:4:58)
(node:58) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3)
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

```

</details>

## 7. 其他信息
有相关bug 的背景信息，可以在这里说明

[bug]

**Comment by windmemory** [comment]
`wechaty-puppet-padpro`前一段时间升级了依赖`rx-queue`

升级内容参考 https://github.com/huan/rx-queue/commits/master

请检查你们的项目内是否有引入`rx-queue`的依赖，并且指定了版本，如果没有的话，请删掉node_modules，package-lock.json后重新安装依赖，保证`rx-queue`版本为`0.8.1`，就不会有这个问题了

**Comment by 3014zhangshuo** [comment]
已修复。升级rx-queue版本为0.8.1
