### ISSUE TITLE
chat迁移到pro之后登录成功后发送消息失败然后重新登录报错

### ISSUE THREAD

**Issue by usersuccess** [botorange/wechaty-puppet-padpro#112]
## 1. 提供你的包版本信息
- wechaty 版本：^ 0.23.40
- wechaty-puppet-padpro 版本：0.0.52
- node 版本： (运行 `node --version` 获取版本)v10.15.0
- 你使用的操作系统：CentOS

## 2. Bug 描述
登录后发送消息给个人或者群组，每分钟发送5条，每条延迟4-8秒，发送几条之后开始报错，找不到包，然后退出登录，重新登录提示频繁，但是在chat上面没有出现这个问题

## 3. 复现的步骤 (或者解决的步骤)

**这一部分非常重要，如果你无法给出复现步骤，我们也很难提供相应的解决办法：**

复现步骤中一定要给出*复现代码*

例子:
- 第一步：登录微信成功
- 第二步：每分钟查询数据库前5条消息轮训发送
- 。。。
# 4. 期待程序运行的结果
登录成功后正常发送消息

## 5. 程序实际运行的结果
请用精简的语言或者截图描述实际运行的结果（**请不要在这里粘贴日志截图**）
发送几条消息后报错退出然后重新登录

## 6. 完整的日志信息：
通过`WECHATY_LOG=silly`设定环境变量，将设置log 等级为 silly，获取最详细的日志信息（默认log 等级为 info）
**请提供完整的日志信息(不要只提供部分的日志截图，请复制粘贴日志内容！)**
<details>
<summary>
Show Logs
</summary>

```shell
0:33:00 INFO WechatGateway sendShort（）因错误而失败：TIMEOUT，重试api。
10:33:00 INFO WechatGateway sendShort（）因错误而失败：TIMEOUT，重试api。
10:33:00 INFO WechatGateway sendShort（）因错误而失败：TIMEOUT，重试api。
10:33:00 INFO WechatGateway sendShort（）因错误而失败：TIMEOUT，重试api。
文字
30：33：10 \ u0004] ndShort收到未知包裹：[126]7e0ffffffff300000000df42080d000000003309a8caefeb00a70400000000~ B 
10:33:10 ERR WechatGateway错误发生在呼叫api：GrpcGetChatRoomMember，params：{“Chatroom”：“11387177820 @ chatroom”} 
UNKNOWN_PACKAGE
30：33：10 \ u0004] ndShort接收未知软件包：[126]7e0ffffffff300000000df42080d000000003309a8caefeb00a70400000000~ B10：33：10 
ERR WechatGateway在调用api时发生错误：GrpcGetChatRoomMember，params：{“Chatroom” ：“12239185117 @chatroom”} 
UNKNOWN_PACKAGE 
30：33：10 \ u0004] ndShort接收未知软件包：[126]7e0ffffffff300000000df42080d000000003309a8caefeb00a70400000000~ B10：33：
10 ERR WechatGateway在调用api时发生错误： GrpcGetChatRoomMember，params：{“Chatroom”：“10511169198 @chatroom”} 
UNKNOWN_PACKAGE 
30：33：10 \ u0004] ndShort收到未知包裹：[126]7e0ffffffff300000000df42080d000000003309a8caefeb00a70400000000~ B
10:33:10 ERR WechatGateway错误发生在呼叫api：GrpcGetChatRoomMember，params：{“Chatroom”：“5195072802 @ chatroom”} 
UNKNOWN_PACKAGE 
30：33：10 \ u0004] ndShort收到未知包裹：[126] 7e0ffffffff300000000df42080d000000003309a8caefeb00a70400000000~ B10：
33：10 ERR WechatGateway在调用api时发生错误：GrpcGetChatRoomMember，params：{“Chatroom”：“5081689160 @chatroom”} 
UNKNOWN_PACKAGE 
10:33:10 INFO PadproManager连接有问题，重置自我恢复连接。
10:33:10 WARN PuppetPadpro startManager（）manager.on（reset）for undefined。重新启动PuppetPadpro ... 
联系<万象新动小婉>退出
10:33:10 INFO Wechaty <Puppet＃0（）/ PuppetPadpro＃0> stop（）v0.23.40正在停止......
10:33:10 WARN PuppetPadpro stop（）在OFF木偶上被调用。等待准备好（关闭）并返回。
10:33:10 INFO CacheManager release（）
10:33:10 WARN PadproManager releaseQueue（）订阅已经发布。
10:33:10 WARN PadproManager releaseQueue（）队列已经发布。
10:33:10 INFO CacheManager release（）
10:33:10 WARN CacheManager init（）CacheManager不存在，无需释放它。
10:33:10 INFO WechatGateway stop（）
10:33:10 INFO WechatGateway initLongSocket（）连接到wechat长主机服务器：long.weixin.qq.com结束。
10:33:10 INFO WechatGateway init（我的token，padpro.botorange.com：6666，undefined）
10:33:10 INFO WechatGateway initLongSocket（）连接到微信长主机服务器：long.weixin.qq.com关闭。
10:33:11 INFO WechatGateway initLongSocket（）连接到微信长主机服务器：long.weixin.qq.com。
10:33:11 WARN PadproGrpc GrpcAutoLogin（）登录失败，结果为：{“longHost”：“long.weixin.qq.com”，“shortHost”：“short.weixin.qq.com”，“status”： - 100 ，“userName”：“wxid_nqluo69ukaw221”，“payload”：“\ n1 \ n \ n \ n30 \ n <Title> </ Title> \ n4 \ n0 \ n0 \ n \ n \ n \ n”} 
10:33 ：11 WARN PadproManager tryAutoLogin接收未知的api通话状态，如果你一直看到这个状态，请向我们提交详细日志问题，我们会尽快修复。
扫描QR码登录：0 
https：//api.qrserver。
10:33:12 ERR WechatGateway在调用api时发生错误：GrpcSyncMessage，params：undefined 
{错误：2 UNKNOWN：无法解析数据。
在
Object.onReceiveStatus（/ home / wangqiang / wechaty-）的Object.exports.createStatusError（/home/wangqiang/wechaty-puppet-padpro/node_modules/_grpc@1.19.0@grpc/src/common.js:91:15）
在interceptingListener._callNext（/home/wangqiang/wechaty-puppet-padpro/node_modules/_grpc@1.19.0@grpc/ ）中的puppet-padpro / node_modules / _grpc @ 1.19.0 @ grpc / src / client_interceptors.js：1204：28）src / client_interceptors.js：568：42）
在InterceptingListener.onReceiveStatus（/home/wangqiang/wechaty-puppet-padpro/node_modules/_grpc@1.19.0@grpc/src/client_interceptors.js:618:8）
在回调（/home/wangqiang/wechaty-puppet-padpro/node_modules/_grpc@1.19.0@grpc/src/client_interceptors.js:845:24）
代码：2，
元数据：
元数据{ 
_internal_repr：
{server：[Array] ，date：[Array]，'content-length'：[Array]}}，
详情：'无法解析数据'。} 
10:33:13 INFO WechatGateway initLongSocket（）连接到wechat长主机服务器：long.weixin.qq.com。

```

</details>

## 7. 其他信息
有相关bug 的背景信息，可以在这里说明
因为在chat上面同样的代码没有问题，在pro出现问题，所以是有新的环境变量需要配置吗？
[bug]

**Comment by windmemory** [comment]
麻烦升级到 `v0.0.58`后再试试看

**Comment by usersuccess** [comment]
好的我升级使试一下

**Comment by usersuccess** [comment]
运行过程中出现这个：
Error: CDNManager sendCdnRequest failed. Retried 5 times.
    at CDNManager.<anonymous> (/home/wangqiang/wechaty-puppet-padpro/node_modules/_wechaty-puppet-padpro@0.0.58@wechaty-puppet-padpro/src/manager/cdn-manager.ts:399:11)
    at Generator.next (<anonymous>)
    at fulfilled (/home/wangqiang/wechaty-puppet-padpro/node_modules/_wechaty-puppet-padpro@0.0.58@wechaty-puppet-padpro/dist/src/manager/cdn-manager.js:4:58)
(node:14803) UnhandledPromiseRejectionWarning: Error: CDNManager sendCdnRequest failed. Retried 5 times.
    at CDNManager.<anonymous> (/home/wangqiang/wechaty-puppet-padpro/node_modules/_wechaty-puppet-padpro@0.0.58@wechaty-puppet-padpro/src/manager/cdn-manager.ts:399:11)
    at Generator.next (<anonymous>)
    at fulfilled (/home/wangqiang/wechaty-puppet-padpro/node_modules/_wechaty-puppet-padpro@0.0.58@wechaty-puppet-padpro/dist/src/manager/cdn-manager.js:4:58)
(node:14803) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14803) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
但是程序没有退出

**Comment by windmemory** [comment]
@usersuccess padpro对于大图片的下载使用了cdn，请参考项目README里面的cdn部分，看看是不是本机IP的获取上有一些问题

**Comment by usersuccess** [comment]
还是这个问题掉线了
12:31:58 INFO PadproManager Connection has problem, reset self to recover the connection.
12:31:58 WARN PuppetPadpro startManager() manager.on(reset) for undefined. Restarting PuppetPadpro ... 
Contact<万象新动 小婉> logout
12:31:58 INFO Wechaty <Puppet#0<PuppetPadpro>()/PuppetPadpro#0> stop() v0.23.40 is stoping ...
12:31:58 WARN PuppetPadpro stop() is called on a OFF puppet. await ready(off) and return.
12:31:58 INFO CacheManager release()
12:31:58 WARN PadproManager releaseQueue() subscriptions have been released.
12:31:58 WARN PadproManager releaseQueue() queues have been released.
12:31:58 INFO CacheManager release()
12:31:58 WARN CacheManager init() CacheManager not exist, no need to release it.
12:31:58 INFO WechatGateway stop()
12:31:58 INFO WechatGateway initLongSocket() connection to wechat long host server: long.weixin.qq.com ended.
12:31:58 INFO WechatGateway init(mytoken, padpro.botorange.com:6666, undefined)
12:31:58 INFO WechatGateway initLongSocket() connection to wechat long host server: long.weixin.qq.com closed.
12:31:58 INFO WechatGateway initLongSocket() connected to wechat long host server: long.weixin.qq.com.
12:31:58 WARN PadproGrpc GrpcAutoLogin() login failed with result: {"longHost":"long.weixin.qq.com","shortHost":"short.weixin.qq.com","status":-100,"userName":"wxid_nqluo69ukaw221","payload":"<e>\n<ShowType>1</ShowType>\n<Content><![CDATA[你操作频率过快，请稍后再试。]]></Content>\n<Url><![CDATA[]]></Url>\n<DispSec>30</DispSec>\n<Title><![CDATA[]]></Title>\n<Action>4</Action>\n<DelayConnSec>0</DelayConnSec>\n<Countdown>0</Countdown>\n<Ok><![CDATA[]]></Ok>\n<Cancel><![CDATA[]]></Cancel>\n</e>\n"}
12:31:58 WARN PadproManager tryAutoLogin receive unknown api call status, if you keep seeing this status, please file an issue with detailed log to us, we will fix it ASAP.
Scan QR Code to login: 0
https://api.qrserver.com/v1/create-qr-code/?data=http%3A%2F%2Fweixin.qq.com%2Fx%2FIc4xbrzfWkc2mcXGsAnK

**Comment by windmemory** [comment]
> 12:31:58 WARN PadproGrpc GrpcAutoLogin() login failed with result: {"longHost":"long.weixin.qq.com","shortHost":"short.weixin.qq.com","status":-100,"userName":"wxid_nqluo69ukaw221","payload":"\n1\n\n\n30\n<Title></Title>\n4\n0\n0\n\n\n\n"}
12:31:58 WARN PadproManager tryAutoLogin receive unknown api call status, if you keep seeing this status, please file an issue with detailed log to us, we will fix it ASAP.

上面这个json里面的payload的内容是什么？有提到”操作频繁“么？

**Comment by usersuccess** [comment]
没有提到频繁操作，但是他还是掉线了

**Comment by usersuccess** [comment]
刚看了一下，里面提到了频繁操作，重新登录后提示了
