### ISSUE TITLE
Introduce wechaty-puppet-padpro to the wechaty-puppet directory

### ISSUE THREAD

**Issue by huan** [botorange/wechaty-puppet-padpro#119]
The official puppet directory is at <https://github.com/Chatie/wechaty-puppet/wiki/Directory>

**Comment by windmemory** [comment]
Updated, please verify.

**Comment by huan** [comment]
It looks great, thank you very much for updating the directory.

I have another question: had we officially deprecated the padchat puppet? If so, I'd like to invite you to add a `DEPRECATED` flag to the puppet directory page, for the padchat puppet.

**Comment by windmemory** [comment]
We haven't officially deprecate the padchat puppet, I will put a DEPRECATED flag to the puppet directory page.

**Comment by windmemory** [comment]
Tag added, please check.

**Comment by huan** [comment]
What tag added to where, and what do you want me to check about?

Please help me to understand you clearly, thank you very much.

![image](https://user-images.githubusercontent.com/1361891/62443892-a69c2200-b78e-11e9-8f9b-ec358233836d.png)

**Comment by windmemory** [comment]
I added tag to the puppet directory page: https://github.com/Chatie/wechaty-puppet/wiki/Directory

![image](https://user-images.githubusercontent.com/6801292/62444026-faa70680-b78e-11e9-917f-4233e4ddbc79.png)

**Comment by huan** [comment]
Ok, got it, thanks.

I'd like to suggest you to consider adding a `deprecated` warning to the npm module `wechaty-puppet-padchat` by:

```sh
npm deprecate wechaty-puppet-padchat 'some words like wechaty-puppet-padchat was deprecated. use wechaty-puppet-padpro instead'
```

**Comment by windmemory** [comment]
Oh, got it, that's really something that we ought to add. Thanks for the suggestion! You are the best.

**Comment by huan** [comment]
Great. Thank you for pushing this forward, this issue had been solved.
