### ISSUE TITLE
room-leave 管理员删除用户事件捕获不到，room-join事件正常

### ISSUE THREAD

**Issue by god-bless-me** [botorange/wechaty-puppet-padpro#128]
> 重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

## 0. 发 Issue 指南

1. 请运行下面的命令，看问题是否可以被解决：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```
已运行没有解决
2. 请在 [FAQ 清单](https://docs.chatie.io/v/zh/faq) 看是否已有解决办法。

3. 请先在issue 中搜关键信息，确认你要发的内容和之前的issue 不重复。

## 1. 提供你的包版本信息
- wechaty 版本：0.26.1
- wechaty-puppet-padpro 版本：0.2.1
- node 版本： (运行 `node --version` 获取版本)v10.15.1
- 你使用的操作系统：windows

## 2. Bug 描述
room-leave 管理员删除用户事件捕获不到,没有升级之前是可以的，升级之后就捕获不到了

## 3. 复现的步骤 (或者解决的步骤)

**这一部分非常重要，如果你无法给出复现步骤，我们也很难提供相应的解决办法：**

复现步骤中一定要给出*复现代码*

.on('room-leave', async function(room, leaverList) {
  log.info('Bot', 'EVENT: room-leave - Room "%s" lost member "%s"',
                  await room.topic(),
                  leaverList.map(c => c.name()).join(','),
              )
})

## 4. 期待程序运行的结果
可以打印出log

## 5. 程序实际运行的结果
没有打印，后面尝试了其他方式也还是没有任何反应，room-join，message，friendship事件正常，

## 6. 完整的日志信息：
通过`WECHATY_LOG=silly`设定环境变量，将设置log 等级为 silly，获取最详细的日志信息（默认log 等级为 info）
**请提供完整的日志信息(不要只提供部分的日志截图，请复制粘贴日志内容！)**
<details>
<summary>
19:11:34 SILL PadproGrpc GrpcSendMessage(21714536640@chatroom, 谢谢你的鼓励～, u
ndefined)
19:11:34 SILL DedupeApi dedupe() no need to dedupe api GrpcSendMessage.
19:11:34 SILL WechatGateway _callApi(GrpcSendMessage, {"Content":"谢谢你的鼓励～
","MsgSource":"","ToUserName":"21714536640@chatroom"}) the 1 times, booted 34.87
9 seconds since boot.
19:11:34 SILL WechatGateway sendLong() reqSeq: 2325843702
19:11:34 SILL WechatGateway sendLong() receive back package size: 132
19:11:34 SILL GrpcGateway parse(GrpcSendMessage) get response: {"payload":"null"
,"ret":0}
19:11:34 VERB PuppetPadpro Send Message results: {"payload":"null","ret":0}
19:11:34 VERB PuppetPadpro roomMemberList(21714536640@chatroom)
19:11:34 VERB PadproManager getRoomMemberIdList(21714536640@chatroom)
19:11:34 VERB PadproManager getRoomMemberIdList(21714536640@chatroom) length=4
19:11:34 SILL PuppetPadpro roomMemberList() = 4
19:11:46 SILL PadproManager syncMessage()
19:11:46 SILL DedupeApi dedupe() no need to dedupe api GrpcSyncMessage.
19:11:46 SILL WechatGateway _callApi(GrpcSyncMessage, undefined) the 11 times, b
ooted 47.078 seconds since boot.
19:11:46 SILL WechatGateway sendLong() reqSeq: 3771311493
19:11:46 SILL WechatGateway sendLong() receive back package size: 246
19:11:46 SILL GrpcGateway parse(GrpcSyncMessage) get response: {"data":null}
19:11:46 VERB PadproManager syncMessage() got 0 message(s).
19:11:47 SILL PadproManager syncMessage()
19:11:47 SILL DedupeApi dedupe() no need to dedupe api GrpcSyncMessage.
19:11:47 SILL WechatGateway _callApi(GrpcSyncMessage, undefined) the 12 times, b
ooted 48.26 seconds since boot.
19:11:47 SILL WechatGateway sendLong() reqSeq: 2969809201
19:11:47 SILL WechatGateway sendLong() receive back package size: 470
19:11:47 SILL GrpcGateway parse(GrpcSyncMessage) get response: {"data":[{"MsgTyp
e":2,"UserName":"21714536640@chatroom","NickName":"","Signature":"","SmallHeadIm
gUrl":"","BigHeadImgUrl":"","Province":"","City":"","Remark":"","Alias":"","Sex"
:0,"ContactType":0,"Ver
19:11:47 VERB PadproManager syncMessage() got 1 message(s).
19:11:47 VERB RoomConverter convertRoom() use alternative way to convert.
19:11:47 SILL PadproManager syncRoomMember(21714536640@chatroom)
19:11:47 SILL PadproGrpc GrpcGetChatRoomMember(21714536640@chatroom)
19:11:47 SILL DedupeApi dedupeApi(GrpcGetChatRoomMember, {"Chatroom":"2171453664
0@chatroom"})
19:11:47 SILL DedupeApi dedupeApi(GrpcGetChatRoomMember) dedupe api call missed,
 call the external service.
19:11:47 SILL WechatGateway _callApi(GrpcGetChatRoomMember, {"Chatroom":"2171453
6640@chatroom"}) the 37 times, booted 48.55 seconds since boot.
19:11:47 SILL PadproManager syncMessage()
19:11:47 SILL WechatGateway sendShort() res: commandUrl: /cgi-bin/micromsg-bin/g
etchatroommemberdetail
19:11:48 SILL GrpcGateway parse(GrpcGetChatRoomMember) get response: {"ChatroomU
sername":"21714536640@chatroom","ServerVersion":700000024,"MemberDetails":[{"Use
rname":"wxid_529vfo48n59h22","NickName":"星辉科技","DisplayName":"","BigHeadImgU
rl":"http://wx.qlogo.cn/mmhead/ve
19:11:48 SILL DedupeApi dedupeApi(GrpcGetChatRoomMember) got results from extern
al service, resolve 0 duplicate api calls.
19:11:48 SILL PadproManager syncRoomMember(21714536640@chatroom) total 3 members

19:11:48 VERB RoomConverter convertRoom() use alternative way to convert.
19:11:48 SILL DedupeApi dedupe() no need to dedupe api GrpcSyncMessage.
19:11:48 SILL WechatGateway _callApi(GrpcSyncMessage, undefined) the 13 times, b
ooted 49.262 seconds since boot.
19:11:48 SILL WechatGateway sendLong() reqSeq: 467192086
19:11:48 SILL WechatGateway sendLong() receive back package size: 598
19:11:48 SILL GrpcGateway parse(GrpcSyncMessage) get response: {"data":[{"MsgTyp
e":2,"UserName":"21714536640@chatroom","NickName":"","Signature":"","SmallHeadIm
gUrl":"","BigHeadImgUrl":"http://wx.qlogo.cn/mmcrhead/F846hp4K6pEW2ogy0URv0FqhUe
SHShrRoa2cD2liaHdv3myPz
19:11:48 VERB PadproManager syncMessage() got 1 message(s).
19:11:48 VERB RoomConverter convertRoom() use alternative way to convert.
19:11:48 SILL PadproManager syncRoomMember(21714536640@chatroom)
19:11:48 SILL PadproGrpc GrpcGetChatRoomMember(21714536640@chatroom)
19:11:48 SILL DedupeApi dedupeApi(GrpcGetChatRoomMember, {"Chatroom":"2171453664
0@chatroom"})
19:11:48 SILL DedupeApi dedupeApi(GrpcGetChatRoomMember) dedupe api call with ex
isting results.
19:11:48 SILL PadproManager syncRoomMember(21714536640@chatroom) total 3 members

19:11:48 VERB RoomConverter convertRoom() use alternative way to convert.
</summary>
```shell
$ WECHATY_LOG=silly node yourbot.js

```

</details>

## 7. 其他信息
有相关bug 的背景信息，可以在这里说明

[bug]

**Comment by windmemory** [comment]
Please verify if the event is pushed on the phone with bot's wechat account. If the event doesn't pushed to the phone, means that WeChat didn't push the messages, thus `wechaty` can not catch this event.

**Comment by windmemory** [comment]
Close this issue since no active since last month.
