### ISSUE TITLE
room.del()无法删除群内成员  机器人为管理员

### ISSUE THREAD

**Issue by god-bless-me** [botorange/wechaty-puppet-padpro#129]
> 重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

## 0. 发 Issue 指南

1. 请运行下面的命令，看问题是否可以被解决：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. 请在 [FAQ 清单](https://docs.chatie.io/v/zh/faq) 看是否已有解决办法。
无法结局
3. 请先在issue 中搜关键信息，确认你要发的内容和之前的issue 不重复。

## 1. 提供你的包版本信息
- wechaty 版本：0.26.1
- wechaty-puppet-padpro 版本：0.2.1
- node 版本： (运行 `node --version` 获取版本)v10.15.1
- 你使用的操作系统：windows

## 2. Bug 描述
room.del()无法删除群内成员  机器人为管理员，按照文档要求机器人为管理员时应该是可以删除的

## 3. 复现的步骤 (或者解决的步骤)

**这一部分非常重要，如果你无法给出复现步骤，我们也很难提供相应的解决办法：**

复现步骤中一定要给出*复现代码*

例子:
- 第一步：
const bot = new Wechaty()
await bot.start()
// after logged in...
const room = await bot.Room.find({topic: 'wechat'})          // change 'wechat' to any room topic in your wechat
const contact = await bot.Contact.find({name: 'A'})   // change 'lijiarui' to any room member in the room you just set
if (room) {
  try {
     await room.del(contact)
  } catch(e) {
     console.error(e)
  }
}

## 4. 期待程序运行的结果
可以进行A成员的删除

## 5. 程序实际运行的结果
请用精简的语言或者截图描述实际运行的结果（**请不要在这里粘贴日志截图**）

## 6. 完整的日志信息：
通过`WECHATY_LOG=silly`设定环境变量，将设置log 等级为 silly，获取最详细的日志信息（默认log 等级为 info）
**请提供完整的日志信息(不要只提供部分的日志截图，请复制粘贴日志内容！)**
<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

```
16:01:22 SILL Puppet roomMemberPayload(22805536633@chatroom) cache SET
16:01:22 SILL Puppet roomMemberPayload(22805536633@chatroom) cache SET
16:01:22 SILL Puppet roomMemberPayload(22805536633@chatroom) cache SET
16:01:22 SILL Puppet roomMemberPayload(22805536633@chatroom) cache SET
16:01:22 SILL Puppet roomMemberPayload(22805536633@chatroom) cache SET
16:01:22 VERB Puppet roomMemberSearch(22805536633@chatroom, {"name":"A"})
16:01:22 VERB Puppet contactSearch(query={"name":"A"}, idList.length = 5)
16:01:22 SILL Puppet contactSearch() searchIdList.length = 5
16:01:22 VERB Puppet contactQueryFilterFactory({"name":"A"})
16:01:22 SILL Puppet contactPayload(wxid_nrhuljdye2l622) cache MISS
16:01:22 SILL Puppet contactPayload(wxid_529vfo48n59h22) cache MISS
16:01:22 SILL Puppet contactPayload(chenhui-hero) cache MISS
16:01:22 SILL Puppet contactPayload(wxid_p86bnddpbkfj22) cache MISS
16:01:22 SILL Puppet contactPayload(newsapp) cache SET
16:01:22 SILL Puppet contactPayload(newsapp) cache SET
16:01:22 SILL Accessory #5<Contact> constructor()
16:01:22 SILL Contact constructor(wxid_vb96x855uslm22)
16:01:22 SILL Contact ready() @ Puppet#0<PuppetPadpro>()/PuppetPadpro#0
16:01:22 SILL Contact ready() @ Puppet#0<PuppetPadpro>()/PuppetPadpro#0
16:01:22 SILL Puppet contactPayload(wxid_nrhuljdye2l622) cache SET
16:01:22 SILL Puppet contactPayload(wxid_529vfo48n59h22) cache SET
16:01:22 SILL Puppet contactPayload(chenhui-hero) cache SET
16:01:22 SILL HotImport initProxyModule() proxyModule()
16:01:22 VERB Puppet selfId()
newsapp info do not reply
16:01:22 SILL HotImport initProxyModule() proxyModule()
16:01:22 VERB Puppet selfId()
newsapp info do not reply
16:01:23 SILL Puppet contactPayload(wxid_p86bnddpbkfj22) cache SET
16:01:23 SILL Puppet contactSearch() searchContactPayloadList.length = 0
16:01:23 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_nrhuljdye2l622)
16:01:23 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_529vfo48n59h22)
16:01:23 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_vb96x855uslm22)
16:01:23 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=ch
enhui-hero)
16:01:23 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_p86bnddpbkfj22)
16:01:23 VERB Puppet roomMemberSearch(22805536633@chatroom, {"contactAlias":"A"}
)
16:01:23 VERB Puppet contactSearch(query={"alias":"A"}, idList.length = 5)
16:01:23 SILL Puppet contactSearch() searchIdList.length = 5
16:01:23 VERB Puppet contactQueryFilterFactory({"alias":"A"})
16:01:23 SILL Puppet contactSearch() searchContactPayloadList.length = 0
16:01:23 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_nrhuljdye2l622)
16:01:23 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_529vfo48n59h22)
16:01:23 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_vb96x855uslm22)
16:01:23 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=ch
enhui-hero)
16:01:23 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_p86bnddpbkfj22)
16:01:23 VERB Puppet roomMemberSearch(22805536633@chatroom, undefined)
16:01:23 VERB Puppet roomMemberPayloadDirty(22805536633@chatroom)
16:01:24 VERB Puppet roomPayloadDirty(22805536633@chatroom)
16:01:24 SILL Accessory #6<Room> constructor()
16:01:24 SILL Room constructor(22805536633@chatroom)
16:01:24 VERB Room ready()
16:01:24 VERB Puppet roomPayloadDirty(22805536633@chatroom)
16:01:24 VERB Puppet roomMemberPayloadDirty(22805536633@chatroom)
16:01:24 VERB Puppet roomPayload(22805536633@chatroom)
16:01:24 SILL Puppet roomPayloadCache(22805536633@chatroom) cache MISS
16:01:25 SILL Puppet roomPayload(22805536633@chatroom) cache SET
16:01:25 SILL Accessory #7<Contact> constructor()
16:01:25 SILL Contact constructor(chenhui-hero)
16:01:25 SILL Accessory #8<Contact> constructor()
16:01:25 SILL Contact constructor(wxid_p86bnddpbkfj22)
16:01:25 SILL Accessory #9<Contact> constructor()
16:01:25 SILL Contact constructor(wxid_nrhuljdye2l622)
16:01:25 SILL Accessory #10<Contact> constructor()
16:01:25 SILL Contact constructor(wxid_529vfo48n59h22)
16:01:25 SILL Contact ready() @ Puppet#0<PuppetPadpro>()/PuppetPadpro#0
16:01:25 SILL Contact ready() isReady() true
16:01:25 SILL Contact ready() @ Puppet#0<PuppetPadpro>()/PuppetPadpro#0
16:01:25 SILL Contact ready() @ Puppet#0<PuppetPadpro>()/PuppetPadpro#0
16:01:25 SILL Contact ready() @ Puppet#0<PuppetPadpro>()/PuppetPadpro#0
16:01:25 SILL Contact ready() @ Puppet#0<PuppetPadpro>()/PuppetPadpro#0
16:01:25 SILL Contact ready() @ Puppet#0<PuppetPadpro>()/PuppetPadpro#0
16:01:25 SILL Contact ready() isReady() true
16:01:25 SILL HotImport initProxyModule() proxyModule()
16:01:25 VERB Puppet selfId()
16:01:31 INFO PadproManager initData() finished with contacts: 351, rooms: 38
16:01:35 VERB Puppet roomMemberSearch(22805536633@chatroom, "A")
16:01:35 VERB Puppet roomMemberSearch(22805536633@chatroom, {"roomAlias":"A"})
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_vb96x855uslm22)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=ch
enhui-hero)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_p86bnddpbkfj22)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_nrhuljdye2l622)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_529vfo48n59h22)
16:01:35 SILL Puppet roomMemberPayload(22805536633@chatroom) cache SET
16:01:35 SILL Puppet roomMemberPayload(22805536633@chatroom) cache SET
16:01:35 SILL Puppet roomMemberPayload(22805536633@chatroom) cache SET
16:01:35 SILL Puppet roomMemberPayload(22805536633@chatroom) cache SET
16:01:35 SILL Puppet roomMemberPayload(22805536633@chatroom) cache SET
16:01:35 VERB Puppet roomMemberSearch(22805536633@chatroom, {"name":"A"})
16:01:35 VERB Puppet contactSearch(query={"name":"A"}, idList.length = 5)
16:01:35 SILL Puppet contactSearch() searchIdList.length = 5
16:01:35 VERB Puppet contactQueryFilterFactory({"name":"A"})
16:01:35 SILL Puppet contactSearch() searchContactPayloadList.length = 0
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_vb96x855uslm22)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=ch
enhui-hero)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_p86bnddpbkfj22)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_nrhuljdye2l622)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_529vfo48n59h22)
16:01:35 VERB Puppet roomMemberSearch(22805536633@chatroom, {"contactAlias":"A"}
)
16:01:35 VERB Puppet contactSearch(query={"alias":"A"}, idList.length = 5)
16:01:35 SILL Puppet contactSearch() searchIdList.length = 5
16:01:35 VERB Puppet contactQueryFilterFactory({"alias":"A"})
16:01:35 SILL Puppet contactSearch() searchContactPayloadList.length = 0
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_vb96x855uslm22)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=ch
enhui-hero)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_p86bnddpbkfj22)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_nrhuljdye2l622)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_529vfo48n59h22)
16:01:35 VERB Puppet roomMemberPayloadDirty(22805536633@chatroom)
16:01:35 VERB Puppet roomMemberSearch(22805536633@chatroom, "A")
16:01:35 VERB Puppet roomMemberSearch(22805536633@chatroom, {"roomAlias":"A"})
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_h2bh0rztxikj22)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_vb96x855uslm22)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=ch
enhui-hero)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_p86bnddpbkfj22)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_nrhuljdye2l622)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_529vfo48n59h22)
16:01:35 SILL Puppet roomMemberPayload(22805536633@chatroom) cache SET
16:01:35 SILL Puppet roomMemberPayload(22805536633@chatroom) cache SET
16:01:35 SILL Puppet roomMemberPayload(22805536633@chatroom) cache SET
16:01:35 SILL Puppet roomMemberPayload(22805536633@chatroom) cache SET
16:01:35 SILL Puppet roomMemberPayload(22805536633@chatroom) cache SET
16:01:35 SILL Puppet roomMemberPayload(22805536633@chatroom) cache SET
16:01:35 VERB Puppet roomMemberSearch(22805536633@chatroom, {"name":"A"})
16:01:35 VERB Puppet contactSearch(query={"name":"A"}, idList.length = 6)
16:01:35 SILL Puppet contactSearch() searchIdList.length = 6
16:01:35 VERB Puppet contactQueryFilterFactory({"name":"A"})
16:01:35 SILL Puppet contactPayload(wxid_h2bh0rztxikj22) cache MISS
16:01:35 SILL Puppet contactPayload(wxid_h2bh0rztxikj22) cache SET
16:01:35 SILL Puppet contactSearch() searchContactPayloadList.length = 1
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_h2bh0rztxikj22)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_vb96x855uslm22)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=ch
enhui-hero)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_p86bnddpbkfj22)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_nrhuljdye2l622)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_529vfo48n59h22)
16:01:35 VERB Puppet roomMemberSearch(22805536633@chatroom, {"contactAlias":"A"}
)
16:01:35 VERB Puppet contactSearch(query={"alias":"A"}, idList.length = 6)
16:01:35 SILL Puppet contactSearch() searchIdList.length = 6
16:01:35 VERB Puppet contactQueryFilterFactory({"alias":"A"})
16:01:35 SILL Puppet contactSearch() searchContactPayloadList.length = 0
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_h2bh0rztxikj22)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_vb96x855uslm22)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=ch
enhui-hero)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_p86bnddpbkfj22)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_nrhuljdye2l622)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_529vfo48n59h22)
16:01:35 VERB Puppet roomMemberSearch(22805536633@chatroom, "喜剧之王")
16:01:35 VERB Puppet roomMemberSearch(22805536633@chatroom, {"roomAlias":"喜剧之
王"})
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_h2bh0rztxikj22)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_vb96x855uslm22)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=ch
enhui-hero)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_p86bnddpbkfj22)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_nrhuljdye2l622)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_529vfo48n59h22)
16:01:35 VERB Puppet roomMemberSearch(22805536633@chatroom, {"name":"喜剧之王"})

16:01:35 VERB Puppet contactSearch(query={"name":"喜剧之王"}, idList.length = 6)

16:01:35 SILL Puppet contactSearch() searchIdList.length = 6
16:01:35 VERB Puppet contactQueryFilterFactory({"name":"喜剧之王"})
16:01:35 SILL Puppet contactSearch() searchContactPayloadList.length = 1
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_h2bh0rztxikj22)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_vb96x855uslm22)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=ch
enhui-hero)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_p86bnddpbkfj22)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_nrhuljdye2l622)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_529vfo48n59h22)
16:01:35 VERB Puppet roomMemberSearch(22805536633@chatroom, {"contactAlias":"喜
剧之王"})
16:01:35 VERB Puppet contactSearch(query={"alias":"喜剧之王"}, idList.length = 6
)
16:01:35 SILL Puppet contactSearch() searchIdList.length = 6
16:01:35 VERB Puppet contactQueryFilterFactory({"alias":"喜剧之王"})
16:01:35 SILL Puppet contactSearch() searchContactPayloadList.length = 0
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_h2bh0rztxikj22)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_vb96x855uslm22)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=ch
enhui-hero)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_p86bnddpbkfj22)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_nrhuljdye2l622)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_529vfo48n59h22)
16:01:35 VERB Puppet roomMemberPayloadDirty(22805536633@chatroom)
16:01:35 VERB Puppet roomPayloadDirty(22805536633@chatroom)
16:01:35 VERB Room ready()
16:01:35 VERB Puppet roomPayloadDirty(22805536633@chatroom)
16:01:35 VERB Puppet roomMemberPayloadDirty(22805536633@chatroom)
16:01:35 VERB Puppet roomPayload(22805536633@chatroom)
16:01:35 SILL Puppet roomPayloadCache(22805536633@chatroom) cache MISS
16:01:35 SILL Puppet roomPayload(22805536633@chatroom) cache SET
16:01:35 SILL Accessory #11<Contact> constructor()
16:01:35 SILL Contact constructor(wxid_h2bh0rztxikj22)
16:01:35 SILL Contact ready() @ Puppet#0<PuppetPadpro>()/PuppetPadpro#0
16:01:35 SILL Contact ready() @ Puppet#0<PuppetPadpro>()/PuppetPadpro#0
16:01:35 SILL Contact ready() isReady() true
16:01:35 SILL Contact ready() @ Puppet#0<PuppetPadpro>()/PuppetPadpro#0
16:01:35 SILL Contact ready() isReady() true
16:01:35 SILL Contact ready() @ Puppet#0<PuppetPadpro>()/PuppetPadpro#0
16:01:35 SILL Contact ready() isReady() true
16:01:35 SILL Contact ready() @ Puppet#0<PuppetPadpro>()/PuppetPadpro#0
16:01:35 SILL Contact ready() isReady() true
16:01:35 SILL Contact ready() @ Puppet#0<PuppetPadpro>()/PuppetPadpro#0
16:01:35 SILL Contact ready() isReady() true
16:01:35 SILL Contact ready() @ Puppet#0<PuppetPadpro>()/PuppetPadpro#0
16:01:35 SILL Contact ready() isReady() true
16:01:35 SILL Contact ready() @ Puppet#0<PuppetPadpro>()/PuppetPadpro#0
16:01:35 SILL Contact ready() isReady() true
16:01:35 SILL HotImport initProxyModule() proxyModule()
16:01:35 VERB Room topic()
16:01:35 VERB Room owner()
16:01:35 SILL Room memberAll({"name":"A"})
16:01:35 VERB Puppet roomMemberSearch(22805536633@chatroom, {"name":"A"})
16:01:35 VERB Puppet contactSearch(query={"name":"A"}, idList.length = 6)
16:01:35 SILL Puppet contactSearch() searchIdList.length = 6
16:01:35 VERB Puppet contactQueryFilterFactory({"name":"A"})
16:01:35 SILL Puppet contactSearch() searchContactPayloadList.length = 1
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_h2bh0rztxikj22)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_vb96x855uslm22)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=ch
enhui-hero)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_p86bnddpbkfj22)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_nrhuljdye2l622)
16:01:35 VERB Puppet roomMemberPayload(roomId=22805536633@chatroom, contactId=wx
id_529vfo48n59h22)
16:01:35 SILL Puppet roomMemberPayload(22805536633@chatroom) cache SET
16:01:35 SILL Puppet roomMemberPayload(22805536633@chatroom) cache SET
16:01:35 SILL Puppet roomMemberPayload(22805536633@chatroom) cache SET
16:01:35 SILL Puppet roomMemberPayload(22805536633@chatroom) cache SET
16:01:35 SILL Puppet roomMemberPayload(22805536633@chatroom) cache SET
16:01:35 SILL Puppet roomMemberPayload(22805536633@chatroom) cache SET
16:01:35 VERB Room del(Contact<A>)
16:02:07 SILL Wechaty memoryCheck() free: 3718 MB, require: 4 MB

</details>

## 7. 其他信息
有相关bug 的背景信息，可以在这里说明

[bug]

**Comment by windmemory** [comment]
![image](https://user-images.githubusercontent.com/6801292/57969686-2692c700-79ac-11e9-92e8-7aeb3da3f17d.png)

文档上写的是群主的时候生效，管理员我们没有测试过

**Comment by windmemory** [comment]
@god-bless-me 关于这个issue还有什么问题么？

**Comment by windmemory** [comment]
Close this issue since no active for last month.
