### ISSUE TITLE
pad_pro发送语音文件没有任何报错，语音文件没有发送出来

### ISSUE THREAD

**Issue by god-bless-me** [botorange/wechaty-puppet-padpro#133]
> 重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

## 0. 发 Issue 指南

1. 请运行下面的命令，看问题是否可以被解决：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. 请在 [FAQ 清单](https://docs.chatie.io/v/zh/faq) 看是否已有解决办法。

3. 请先在issue 中搜关键信息，确认你要发的内容和之前的issue 不重复。

## 1. 提供你的包版本信息
- wechaty 版本：0.26.1
- wechaty-puppet-padpro 版本：0.2.1
- node 版本： (运行 `node --version` 获取版本)v11.0.0
- 你使用的操作系统：centos7

## 2. Bug 描述
请用精简的语言描述你遇到的bug
pad_pro发送语音文件没有任何报错，语音文件没有发送出来
## 3. 复现的步骤 (或者解决的步骤)

**这一部分非常重要，如果你无法给出复现步骤，我们也很难提供相应的解决办法：**

复现步骤中一定要给出*复现代码*

例子:
本地已经保存好slk语音文件，使用如下代码：
                  const fileBox = FileBox.fromFile('../uploads/user/3/slk/1558621071.slk')

                    room.say(fileBox)

## 4. 期待程序运行的结果
希望群中能收到语音文件

## 5. 程序实际运行的结果
请用精简的语言或者截图描述实际运行的结果（**请不要在这里粘贴日志截图**）

## 6. 完整的日志信息：
通过`WECHATY_LOG=silly`设定环境变量，将设置log 等级为 silly，获取最详细的日志信息（默认log 等级为 info）
**请提供完整的日志信息(不要只提供部分的日志截图，请复制粘贴日志内容！)**
<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

```
../uploads/user/3/slk/1558621071.slk
get in real
22:27:55 VERB PuppetPadpro messageSendFile("{"roomId":"13646972688@chatroom"}", FileBox#File<1558621071.slk>)
22:27:55 SILL PuppetPadpro fileType .slk
22:27:55 SILL PadproGrpc GrpcSendVoice(13646972688@chatroom, voice, 1558621071)
22:27:55 SILL DedupeApi dedupe() no need to dedupe api GrpcSendVoice.
22:27:55 SILL WechatGateway _callApi(GrpcSendVoice, {"Data":"AiMhU0lMS19WMwwApyt096juSeXgI3BDCwCnK3T3qZynot6/PxAApzY386S+Q1k8Mh272WBA2Q8Ap/+iA6iZ544Hp1ZrMLS/FQCoNaZv26ksEP3q3feo3X8UV5GVVb0TAKl2znDCT+cBR7z+cnixSEXSBFckAKuUknAZOlHohpJ0iYt8HIJn55HR0jmJszv8J+fbYr0xh2B+PyQArfD1qfIwIEys7BKZz0l0qEqkioDhVgYph66FVGD9twA3mDe/IQCwGswJ0EnYYxSCdaut3Ad5Ij/p9RKMwAAehlmbxZg+5z8nALFMQvmOuuLCYI8o/og4146EgCTUAdJkaJdBv4k1Hibhr1ke2zHPfyAAscGi9/w9QUBzZ/yx/x8lcmChz4KBYAqjMgKbWDq7DccgALIrgHqsW27/m4WiJP3tFFsva3Wpk0btOIoxVCh0LBxKIQCyBpyYBoIji51/xJg0WNI2ux8EFkhqTWGUo7SIU5ytdj8kAKWnXO/e6npoZteXslHZIlDWrL1gdK3bxBSbeg/b1d3HpcA0pyYAj1O7Lksv8w+94HPdv/yFYZ/x11Gb2zO07k0fVED9T5N42Oncxn8rAJBA7Wy9gVyL9aJb8uNu/Y9nOm7SRl+cN4bhnsRN9CJinYsMRzR96Hl/R5sqAJA5cGWzKhaAuJkL7p3v0kAnamN9iHbbTLVnMGzndObWlFP2DkGjcmGGvzIAkGdc3jVSHooWN+Q+XSXADyJ8slIRntv/GQ0a52Idl51mlI5U4cVUfyO6gnL2sRJb9P8tAJL/+Y3KZjpMg0YoQqXAdho/GCxP+hjeDJxRXzgwaGllCM/oeEk5Lr0DUhHLnyUAkw9ORbzJ22plBKKkRvNtJrUkv8yaoK0Qq+Nd0qpiAyAnPLh4DyIAkuLKJ4WnDOtUuaGNNIGzpL4O7nF7iUFfqylEgLvtJfKRPyUAkDl461S1M39zZpKLtsWywjRf2k7c/nbdDdTWCPq5RWP8cwB/3yMAjvJwPskQLiXjnc/v6Q+EFEZwDWNGhDpfyucwiVhlOKqHPH8gAI7BZUyVnd6fg0z4w4MCRU9rACFYs0i3a87tibwcRtDTIQCNhacOpH9d/MxCUGeYzbpaP5xVDfwl3hzr7lMp2CiMq98nAIvDfpb7qYkdihtEjyNmgu0Zpja1oZsVqyyWcYJ1zfbxh+A+VVMrIyEAiuV7IFcv8xFUo5pKJsXUll/iJQGcSjuoqDWfoomOV2evIgCK5OaN62zg3nw6OLo0eNHieDLGzxTA1JvCtnr7018y1lXPIwCJRdoL4olY6p/E3YiEl0W1kDvP2Xs7JEkHpRAhPHtaZAFz/yMAskd4kUCW1MtJAitvqhATULuASSTAvDqx5QwrTUmNZNrV238jALYoI5lfuZwbRXofLChjx7p9qViqcBVl/DPdSBAg+X4igBuFKACmXnmKr9XzfWoG/o2groESobTS92Qf5peEOLx/fFVjkzZ6bUfunbj/KQCVuqncHLCfX6sEtztWm9dfAY6YjvIcknqWF1KFpwyb9YkUqcZwELJavyoAlXjex3ZlWJnKEXG+wFByd8k0LnDTbw5hW4YGHk1dEQj47tNvlq4q+8rPKACRIgNRELwlDkI953GPfb783wJ8vthy8UNuoupdqUJTlOIeu2zmKnB/HQCQPp/8yUUS0i10eokMIg7LL5lzTYcEeIGJNh/ALyMAjr4hxdjD299iUzieWkdItTp66NEOfImKKKhH2+T6mWZnv38gAI2NBePfd4CFRx3I2yuaVre0xwRRSn3/itMr0zlQgeV/IwCMPEObr+vjFadFftNFpeCsruyFbNSAmpYSXuitnWOs89JRVx0Ai/Or3n4Z1AteRnFMFDSF79tNWgZ/oe3R4uImF3QhAIrMOnc//1vwfjPuxnRtj96HiFqE0iSFJeVAtJ66qsp1fysAiZbYWizXNU/C/HcIVxz6ffPmxAYAE5clc84GJXhUGOGdVTO03WUTA7unDyQAiHqfZJp4ulTPO2/5yY/l+JWDJFyZsepquBWdmRIjRz1XVtViKQCIFkN4qAePgwdkA74FJQ163LNziwCgkChuLSsjTDojR9pzIUCzIOUvfyEAhvssgew1yDOnQ5jSMbJF1zgXnWUVhkSrCFmCoztnvESfGgCGP8k439w1OjTDfbcrK8byMAAp4I75EBZw/xsAhjZTrLzUsHtc6/uzSReK3QBNfpmH5mPbTEhvFwCGNtwS863nJ0h9qtRo76LMVJJDQ5JIfx0Aheg6Px9EMZ/+w7L919eW8u/XBkDuweBWg0DLMF8ZAIU+Jdzre+LKDrJkjurxaQA7SjJzK446xb8nAIZCNUTlmcEs+lZ4N57pY83HCPzcma85ZjiM7pS1BXmKXYqf8PDyOykAh6Z0KsIr2HmPJU8yYR4qcvJ7dJmfGTtB0GeVYmoUxStgVRauP2canX8kAItdpI1E9Q7hSEVnkGMNgtFfZ2w4QtzDKT8HS4lVbV5tP98oXygAjDyqSg4jNXq84z1QYvMirZRfi42bkH5ujM459Wy0ZXGbwBoSFGd+jyQAjDyqVABuIaAazZXisMvNaRVwS8yUkeCsatKDH8C1visQhgHxJgCPKxv1+UCpZ4QTpyi4pGykxNgLSgWnrbGjawBQzbze7AG+dS36WScAthP1GJZNxRBNVEGtTMdjS7mZnAH7E4pPz+NImuB+1H+JvtP22ztnJAC3L6i6iNYTv4siA//Q5gFb7eAOY6+6wQpLiYtBceUwjp2knC0fALdM7YFqR4GwoNEa8CFiF7T0T3BXJoSBKmbAqTKSmK8fAKYTx+qQE74ehakwBbP+LdY8jeqrIK1jP1/FiyoGA/8nAJBSmeUqeog1omBffjyp8OZZ7zQ8jpK+lh6IcNC8OM3+/uCW+vqjfx8AjvYBjyLs6K7QnEG+m+k6CYzFw26xia8DZps+sbnerxkAjpb1SRKXXfmNHC0kVay9tHCyyJf/+K6mnxgAi70IH1irGVpoG+6Z82Z3KdvXBLd/UQB/HgCIRPF2ogw9cTc6pZi4AE3T+MExEHz27Z/t0oDQ+U8aAIZbQzuskzYsQsnfTmQVd/fzHd05XaXvpB1fFQCGFXo8s7os5joEJgxBCqSf1YFVIJ8bALE4U0LgVyEAQ1FCD1DUzChOa0PsAgPKPcaw9BoAsFt5iN4yjDY7YibkcZP03eSv6JD6PdNY/aMfAKV36q8Vcdo1EmwtzX1uylzDOCHZsCZ8ZK3biLnOrL8oALSSRsN9yEBSjrgtwPznDdbR03hwTKRty09ZXfdgLrBKHDukAYjcma8nALbHkcoEsW4mOGIshUzMVqLkhZWtdM2MlM7Ie5e0S6PNKMw9cByW7x8Atpkh2oV5ocd6taFyvpW3wxVz6nQcV7XsTR48dA5qjyAAj6AB2xKSS9sSCKXictOB31/WrBTCbTTGpauIQmDmuz8lAIp5yzjAzsh1fJkTNOOH+mJrdDNOi307dbUveKj+uwONU/EY2XMeAIhO4UosJpQCytXLUoNDNAcUaFIFVMGzMe5U49+q9R8Ah3FRqq26goVx0kQK+uISqCQGZLkYwUHTPaMZvlOWsSYAh1jT5nek5/8b6DbdtPJQodo+WGaLUNfgiDN3gO25Pt61DFdqOwkeAIjnlUrkzpsyYyj2y6ObDNaAM/6Avk1J61G00PDZLx8Aid+jDbQj7Q806JXOHn2+oB2ZeHFrZ+ktSzPjEi1svx8Aiu9JhCWTFXpvQ/u9PUe96ffDR3m8464KuqcBsidgfyMAinHNB3YTVSo4z1GdI7uNpqZPUlEH4I0BD5l3oP4c/bye/HclAIb6fzssgTX71yPLXx9Yyj49c28oe0pDxENYcEbqTueBNoUiYH8cAIZHBYiG3BT3u79AJYcSZx11ureJSPz6ukX2FO8aAIZHBa+dBUftKQLqnJGYJgnwQRvn/2csrk2/GwCF4LMiy3IWUS9hhBFpFE7Yjky1zIbi4NbxKT8aALDTlxKOf2iE3VcgOaej6EsynXh6JFj6KNVnGwCwcJsiwnyS14LMHySctnTZxPE3r3ydLLlxC48UALBJ+lw4No6ujmriP+PidMOl3fwfHQCwB8wiSfZQ+XMi3GDJjBfzkImG47/yR2pVAKYzuxsAsAG3V4PBNYlB3Wc5H7UyHeEQM9hpTwMokFH/FgCw5Hin18hCZgxACl+cBH0ENGyxquQvDwCxUpL8XgMu+1v3mDWH958SALFR22TnE5XoMthCf2dzg4AWPxMAscHelypxNL5EA+jOadkvF5KqfxMAscINamjyvICxqWTXIopW+lDe3hMAsjM7jwhXEEPkPVRGR4d93F/b/xcAsEtNF6NE8xElsSNLmHRSVm1UWIi0OWIbALAIDc9YGImGoOhBOeA6W+JSNF8gnPJT3xdrfx0AsAgNz1pUx7dQg+7aUs00LlqFuImFauj5gW5UX08VALABqRNmNyeky22fN7VUUPXk7pNmWxkAsAQ2xKVtKUNZFgaPseiG7L98bEQc8wU4rxsAsAQ2xKDxxme0g5xmlyepUNF2ZzIljWqEWk0fGgCwA2B2ZMletyI73KhsCpPOE4ZsMVhbI6pz/yQAsANgeeIODpqdhOkDF7aQtn8ssL6ALymDeJhHkqFVlpRwRJCGHACwcrPwcXnHjcZH30vjygrDe8b+o87kCKmHGhf/IACwcklrYrcZi3PVnSvrEgXFIqLg3uDkQZNTxMoavMeouhQAsHaGJPXdmAJ5RrhyYRU754E0v5scALB2j6Uh3tYTF0QNmxVDMasn76GsH4i8M5wnqhscALADYHbfwGz/R5SBKTcshUMjBs2H0HHsXDMS5f8XALAMRjnL5XV302AdNmDaZVJK5i9kiTHvHACv8ES7jCtFEB85pM9uAkaaT37LmAYwSWo8RBNNJQCmD+7DMallAnecmNbVRgjdCHpoH/3d0CO8iyz9lFpEbKSymKDnJQCVR+NSazIisRpdl+E8VRTJ1mzyiBmbXqtOkArcKA3wleX44gHfKQCSZgSMxldsCpz95z0ACWjWIufyLUhRtvpKlNVMulg4bCDN4AROYFCNvzAAjmTRWYOn2r5xYZ2pKB9zlFZGrvd8Kdjfv1x0VmTuJm8C5+HMKQvFttFA9Dos9jc/JwCNCuqE1JvY4ebEuAkfg9XVwL/HdjEU+0tyxJcS1CLiDaYDygQgZn8oAIsCtPpkUKAoKHCogV27AxkRGqbDL5pl8GZMY05GYQPcU+nJtc7JTecnAIms07AfjhA1wXBrOAZDIxJXKpIhu8i05zfnF4N+N8pqoAHE7VHR2y0AigML2y+cI4zvLq560aWGC7Yw5J2k7tJtdSj3VmgQduMor62U3Jw89ZVwqOS/MACioAAVvBvpYXlLFWZQRZSSFl/JpsZsMufQnF8H3bzha1iqt+YI47feX4EOme81Cv8jALc9fVpm/6JnIBFPXsRLlMGwvuknObmygRksPfZWsWlptyAXIAC3UaItqU+CGaWAnu+hnpbXkH+H7E7fkYHO5VrunhCvWycAj/oRtpDBuuPdtcjkcxhn+4m3B6WSDpyYVhIenyKV+05IY77wAMu/IgCNaDbaSVNujahGcV6BhrnggsCff/MOeSgjRubHdqfAl5fvIwCLquNPi6hpiWURtKtg8/5jInkrR0oIlPYi4K/9kuA0g374/ycAiJdDdEqv3bJd4fyk6TrZYR0bCRBapjwzpNmMq5bMF36qad+UCBz/JAChtAZGycGR9k47WGKdd0R/7OsvCGmucFlBPZ1kgq438l/KAf8dALDeMtKkNY6HALNO1ULGaTYT6vsPkiqHiYvgeHpnGwCwuRuypsUwCT+xH33oKyRATkTwIe3leNl3MXMeALBwkVyxOnzbXKb0q+r59ltBCjlCC9Fy3oX6aO4Vvx4AsEs14wGOJQD+xOZW40MnkGJmtzSqS4wPVBwaF4JXHACwB1TBjdIzetCkpKSalcHD7YBXg2qKfTy4yo7/IQCwGUH7Ql+nGINMQPGHmS11wdo56dHTG6HsR6bXaO0FuacbALAHVJiOQwohTaII4sH2kgxvHspG6TiFCzyWfyAAsAdVCslFhKZs4pYvVEX/De9GwLpvSwVsWxPVVWd2HD8dALAHVQrsa2wNdN7dlg7glC82wx2jIfyFfiegfC3/HwCwENxNjVkdXmzjuzKQ7KPg0weOrsB7QNBguqD9BGKjGwCwdipiLdO2AZu64WQ1q6NxGdHiHKUi3P+tEH8dALB2KlzAybl2KulkkDuOEOZS+4w5fP5wcOECpPj/GwCwcJsr0HsA+peYoqBInMSASePoUa0GD2qJ9TccALB2nyUpQ0YxaKAdRvgEuL+VZuRYUAk5JCPFjz8dALBcy9mcGPFITvmRQxZku2hlZUEfmvccu3YafWa/GgCwB8DT2DZ/0armzu1xveSdbCBMwZZ/ZIJsvxwAsAfKuvSIr2E88mudIpZja1BcBuB45VtEoatfPx4AsAgNx5k8OcAIAP1t1+V3ObrLXAGZg8EAlUVKFIuTHgCwditjdV5BS2Uoag8EN6EP/xLgkPp7PFzNSoXbMv8dALB2lit44olq4XXWymqS9gO3gHDlaXc+kclRW+R/HQCwAwtff2byofGGJQtvbCglZGobAK2jpIdUqJaDySAAsAMLX3zKYmjULrEIlULsNwe0DKWZefMW/4v5vopfqf8cALAYoyHlz5a8DSMzdOismid0GckOaGTItZ408z8cALBJzuxJzh2jksy9LrV6DJDlNLjZcyX7BOQxq9UeALACbk9HhdmcZKE7msgQaG4Ch2uc+89sNycMGPCXLx8AsAdUtF89MOTTVsAJO5e+eZe9rJmjxBGs0PLUE4OQ/xwAsAGfUx2EC/4T1YfB4GxWtPVIzLVdR5akGMLrfx4AsAGfYhYUKjSnu6nJwRfwaDRjnUI6fHtplC/NYzH/HQCwB1YC5wk8mH1x0gNMINh6kYwYXZiq2N4oy68v3xsAsAdUetiy5jKr3gfohBEPrMUly9EPbJEb3YA/HACv2kc7pelcu8loJgjqW4TrqFjN2ttFhWxSnvsfHgCvp69Hgkn+WFYvPaM/ZoMqNFJdRqxGIZOz7BHGAhYfAK+WWSvykHmTST8v2oth0ya+cgczXoIaw/RdmafjpR8iAK+orzFZ1A20Q0NBH52owK3HAlUG5l5VbBAZqAQBf1wzxv8bAK/3uz3JXToIH71aUM0781D1XM0EzRw5++Bhzx0Ar5bRfF182pZ4T/LSnkc1p2ICb0mBTGI32tP6J58hAK+WyaYhtRU8a+9c3LXbkTArcsb20hT8Xac7g1pPZmfDfx0AsAN7e0tPC0/HWrnmO4Di831TdWxDgmFj+Y+14p8bALAHyrrOwGEnv7fuj1NXUQu6lBg/CjSdXH9U/yIAsAN4bv1nw3iwXhXQ+Fd+VYntq7ha3OkxVReYQTAtHqIGfx0AsAfKueTh6U0F0xM46V/77nQwLk4V6x97wgxTasscALAHysPumImlt+RUABpQzz1HZzyteAQqQdWbIKcdALAHysPupZLdomw2YbCpp7R0/fPsgbklxkw3OfX/GgCwB2zLTdYVz95r4En8rHHoev9mYR7JsWGUfxwAr+15tWBJ67IZo08WYGuKjXF9FW4N4RJhxW7evyAAr7eui+zRCdrhgV9MVaV13jl6Z6wnpwZTMDxJKbTWKj8UALFSRZv0AoWJfUKmVtOoQMgHVEbHEgCxY58WsDcznXWLZvkXE0CxMh8SALHCDWxLpzmNOBVcq3FAvp0eFR0Ar9ujR8Ll8zY9BmT3gCO8SF1fxw4qBp/H1nhVCd8bAK+WWNodR0+fPU2ExEBPnAyAfI1CKE3Y6V3mOx4Ar5ZY2w+4MpAKotS0YnyTXyS/fIbz6fYQogZbFsr/GgCwB1RKZgPSZScUQ9uxUISKvfQ3oSIWqLklRx8AsCf22Yo3yvlNT86LnwefZsFTliVKlBulmKu1wffoZyEApXfzzi6+DPJyrjd1PLbrm3TLaorC+mo01AG3nbczmkR/GQCxIPav/wum6vfmp7VCnFJy2vW+wipdJ4//FACxUdut0cC3aCW/eZojVu9E98NEuRUAsVHbnYGpF++VS+x0+Ab/O1LTBxI/","EndFlag":1,"Length":8144,"Offset":0,"ToUserName":"13646972688@chatroom","VoiceFormat":4,"VoiceLength":1558621071}) the 1 times, booted 99.87 seconds since boot.
22:27:55 SILL WechatGateway sendLong() reqSeq: 3238714578
22:27:55 SILL WechatGateway sendLong() receive back package size: 179
22:28:25 SILL PadproManager initQueue() debounceQueue subscribe
22:28:25 SILL PadproGrpc GrpcHeartBeat()
22:28:25 SILL DedupeApi dedupe() no need to dedupe api GrpcHeartBeat.
22:28:25 SILL WechatGateway _callApi(GrpcHeartBeat, undefined) the 3 times, booted 130.034 seconds since boot.
22:28:25 SILL WechatGateway sendLong() reqSeq: 2027959921
22:28:25 SILL PadproManager throttleQueue emit heartbeat.
22:28:25 SILL PuppetPadpro startWatchdog() padproManager.on(heartbeat)
2019-05-23T14:28:25.510Z
22:28:25 SILL WechatGateway sendLong() receive back package size: 20
22:28:25 SILL PadproManager syncMessage()
22:28:25 SILL DedupeApi dedupe() no need to dedupe api GrpcSyncMessage.
22:28:25 SILL WechatGateway _callApi(GrpcSyncMessage, undefined) the 18 times, booted 130.124 seconds since boot.
22:28:25 SILL PadproManager debounceQueue heartbeat result: {"type":"Buffer","data":[0,0,0,20,0,16,0,1,59,154,202,25,120,224,54,113,0,0,0,0]}
22:28:25 SILL PadproManager setContactAndRoomData()
22:28:25 SILL PadproManager setContactAndRoomData() found contact, room, friend data no change.
22:28:25 SILL WechatGateway sendLong() reqSeq: 3883931780
22:28:25 SILL WechatGateway sendLong() receive back package size: 246
22:28:25 SILL GrpcGateway parse(GrpcSyncMessage) get response: {"data":null}
22:28:25 VERB PadproManager syncMessage() got 0 message(s).
</details>

## 7. 其他信息
有相关bug 的背景信息，可以在这里说明

[bug]

**Comment by windmemory** [comment]
语音发送前几天服务器有一些异常，现在已经恢复，请问是否还存在这个发送失败的问题。

**Comment by windmemory** [comment]
Close this issue since no active for last month.
