### ISSUE TITLE
Warning: FlashStoreSync will store all the data in memory

### ISSUE THREAD

**Issue by huan** [botorange/wechaty-puppet-padpro#142]
I saw that we are using `FlashStoreSync` instead of `FlashStore`.

https://github.com/botorange/wechaty-puppet-padpro/blob/43f81fc2a3b246d145f311db517730f4d3ea84f5/src/manager/cache-manager.ts#L5

Just a kind notice that the `FlashStoreSync` will keep all the data in memory so that it might a problem for those users who has lots of Room/Contacts but less memory.

I'd like to suggest we consider to use `FlashStore` instead of `FlashStoreSync` because that will prevent the potential `OOM` problem.

**Comment by windmemory** [comment]
That answers some of the OOM problems that we met before. Will refactor the code and use `FlashStore` later.

**Comment by huan** [comment]
Close this issue because it had been resolved by https://github.com/botorange/wechaty-puppet-padpro/commit/bb22bba4048af11e0f7b48c4dc1d2b361dc06b5b
