### ISSUE TITLE
Upgrade to using Chatie DevOps Toolset

### ISSUE THREAD

**Issue by huan** [botorange/wechaty-puppet-padpro#150]
We have created a new toolset for better DevOps.

Learn more from <https://blog.chatie.io/chatie-devops-toolset/>

The motivation of I create this issue is that it can prevent low-level mistakes like the following:

https://github.com/botorange/wechaty-puppet-padpro/pull/146#pullrequestreview-256044744

I'll submit a PR for this upgrade, hope it can help to improve the code quality in the future.

**Comment by windmemory** [comment]
This is done, `v0.3.8` is using Chatie DevOps Toolset. Close this.

**Comment by huan** [comment]
Great to hear that, good job!

And did you catch more bugs with the help of `@chatie/eslint-config` configuration? It helps me a lot with many minor bugs.

**Comment by windmemory** [comment]
Not really more bugs, but actually some of the rules break the current features, we have to disable some of the rules for specific files, and we did a very careful check on that change to make sure it doesn't break anything.

I do like the idea to make the code rules consistent across our wechaty family, makes it lot easier to work on multiple wechaty projects at the same time.

**Comment by huan** [comment]
I got this <https://github.com/botorange/wechaty-puppet-padpro/pull/158#pullrequestreview-261052339>

Very glad to see that it helped you killed 3 bugs! ;-)

**Comment by windmemory** [comment]
Well,  and those were aware issues, two of them were also caught by the old `tslint`, one was caught by you last time.

Anyway, new `eslint` seems to be more strict, and will help with future development.

**Comment by huan** [comment]
Yes, it's more strict, which is good for us.

And for the "aware issues", I don't think they were "aware" because before using `@chatie/eslint-config`, the CI is green, which means it can be passed by the tslint checking?

**Comment by windmemory** [comment]
Maybe the config is different, I have a workspace config, my local editor shows that as an issue.
