### ISSUE TITLE
换了新的token,提示无效token

### ISSUE THREAD

**Issue by cuiweipeng** [botorange/wechaty-puppet-padpro#152]
ERR PadchatRpc onSocket(payload.type=InvalidPadchatToken) invalid padchat token, payload=-1111({"msgId":"-9007199254740991","data":"","type":-1111,"apiName":null,"userId":"puppet_padpro_XXXXXXXXXXXXX"})
WARN PadchatRpc initWebSocket() ws.on(message) exception: Error:

===========================================================================================

      The token is invalid, please use an valid token to access padchat
      If you have question about this, please check out our wiki:
      https://github.com/lijiarui/wechaty-puppet-padchat/wiki/Buy-Padchat-Token

      您使用的Token是无效的，请您联系我们获取有效Token，详情请参考这个页面：
      https://github.com/lijiarui/wechaty-puppet-padchat/wiki/%E8%B4%AD%E4%B9%B0token

**Comment by windmemory** [comment]
@cuiweipeng log里面看，是因为运行了wechaty-puppet-padchat，但是用的wechaty-puppet-padpro的token，所以提示无效，请使用本项目运行
