### ISSUE TITLE
Please add `wechaty-puppet-padpro` to the Puppet Directory List.

### ISSUE THREAD

**Issue by huan** [botorange/wechaty-puppet-padpro#155]
The new puppet should be added to <https://github.com/Chatie/wechaty-puppet/wiki/Directory> so that the users will discover it from the directory. Because we will always guide the user to the Directory to explore all the puppet providers.

**Comment by windmemory** [comment]
Duplicate with https://github.com/botorange/wechaty-puppet-padpro/issues/119

**Comment by huan** [comment]
We should add `duplicated` tag to this issue too.

**Comment by windmemory** [comment]
Done, thanks @huan
