### ISSUE TITLE
Friendship.add() doesn't work when bot and user are in the same chat group

### ISSUE THREAD

**Issue by lhr0909** [botorange/wechaty-puppet-padpro#29]
Bot and user are not friends, they only share the same chatgroup. 

Logs below:

```
15:42:25 VERB Friendship static add(zhao_cq, Please tell me if this works)
15:42:25 VERB PuppetPadpro friendshipAdd(zhao_cq, Please tell me if this works)
15:42:25 SILL PadproGrpc GrpcSearchContact(zhao_cq)
15:42:25 SILL DedupeApi dedupeApi(GrpcSearchContact, {"Username":"zhao_cq"})15:42:25 SILL DedupeApi dedupeApi(GrpcSearchContact) deduped api call missed, call the external service.15:42:25 SILL WechatGateway sendLong() reqSeq: 2149094824
15:42:25 SILL WechatGateway sendLong() receive back package size: 549
15:42:25 SILL GrpcGateway parse(GrpcSearchContact) get response: {"MsgType":2,"UserName":"v1_f4cee0e00f0e409994bd2fcb7342c08eb13f30a80d20c46afa7f589ec249907c@stranger","NickName":"H.kt","Signature":"What I cannot create, I do not understand","SmallHeadImgUrl":"http
15:42:25 SILL DedupeApi dedupeApi(GrpcSearchContact) got results from external service, resolve 0 duplicate api calls.
15:42:25 WARN PuppetPadpro friendshipAdd zhao_cq has been friend with bot, no need to send friend request!
```

**Comment by windmemory** [comment]
Fixed the issue in the log with 555ba2ffc58f0a602ce0b6898de2bfc63d466175, but still can not add friend, this is a underlying issue, and we are trying to fix this.

**Comment by windmemory** [comment]
This bug should be fixed by `v0.0.54`, please test it with that version. @lhr0909

**Comment by jhmax720** [comment]
This is still happening in version 0.0.56

**Comment by jhmax720** [comment]
Friendship.add() doesn't work when user id start with wxid_xxx

**Comment by windmemory** [comment]
@jhmax720 This is a limitation that wechat has. Currently `wechaty-puppet-padpro` is doing a search with the wechat id to get the contact, then add it as friend, because the contact start with `wxid` can not be searched anymore, so it doesn't work on `wechaty-puppet-padpro`.

We will try to find a way to do this, but the fix time is unknown.

**Comment by jhmax720** [comment]
@windmemory Thank you for clarifying this, is there a way to get group members' real weixin id in a group chat? room.memberAll() currently only return objects with Id like wxid_xxx. There's no way to use Friendship.add() in a group chat. Many thanks

**Comment by windmemory** [comment]
I know the limitation for that. Currently there is no way to get weixin id in a group chat. Although you can get it when you use a real phone or iPad, but the data is loaded in an async way, that means there is another api to get those info, and currently that api hasn't been implemented. Sorry about that.

**Comment by windmemory** [comment]
Close this issue since no more comments for more than a month.

**Comment by jusicorpuz** [comment]
Can someone help me recover my wechat account. It suddenly logged off and said that it was blocked. Please I need to recover it badly. Thanks in advance.

**Comment by windmemory** [comment]
This is not the right place to send such request. @jusicorpuz
