### ISSUE TITLE
weird character inside log

### ISSUE THREAD

**Issue by kis87988** [botorange/wechaty-puppet-padpro#3]
as title. 
Ref https://github.com/botorange/wechaty-puppet-padpro/issues/2 logfile.

**Comment by windmemory** [comment]
This should be fixed :)

**Comment by kis87988** [comment]
reopen this issue becuase the following
![image](https://user-images.githubusercontent.com/25014776/51971052-2a1a3680-242d-11e9-9e9e-6cf9e61c5cf6.png)

**Comment by windmemory** [comment]
The above log issue has been fixed. Please check.

**Comment by windmemory** [comment]
This should be fixed.
