### ISSUE TITLE
discarded message because puppet is not logged-in

### ISSUE THREAD

**Issue by miewx** [botorange/wechaty-puppet-padpro#32]
代码就是readme中的代码，错误见日志，node 11.6.0
https://gist.github.com/miewx/79eb5fb4450e747997daf408f4457c08
代码截图如下

![](https://p.gu321.com/20181227171534.png)

```

  "dependencies": {
    "coffeescript": "^2.3.2",
    "wechaty": "^0.22.6",
    "wechaty-puppet-padpro": "^0.0.28"
  }
```

**Comment by windmemory** [comment]
这个应该是因为获取CDN的DNS信息的时候，首先抓取本机IP的时候没获取到本机的IP，`0.0.31` 更新了自己IP的传入方式，详情参考README
