### ISSUE TITLE
初始化问题

### ISSUE THREAD

**Issue by usersuccess** [botorange/wechaty-puppet-padpro#49]
examples/bot.ts(11,25): error TS2345: Argument of type '{ puppet: "wechaty-puppet-padpro"; puppetOptions: { token: string; }; }' is not assignable to parameter of type 'WechatyOptions'.
  Types of property 'puppet' are incompatible.
    Type '"wechaty-puppet-padpro"' is not assignable to type '"default" | "padchat" | "wechaty-puppet-ioscat" | "wechaty-puppet-mock" | "wechaty-puppet-padchat" | "wechaty-puppet-puppeteer" | "wechaty-puppet-wechat4u" | Puppet | undefined'.

**Comment by kis87988** [comment]
can you also post package.json and what environment that you run the bot?
docker or npm? and OS info.

**Comment by Suley** [comment]
I encountered the same error. 

My package.json:

`
{
  "name": "backend",
  "version": "1.0.0",
  "description": "The Wechat Bot Core Package",
  "main": "index.ts",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "#####"
  },
  "keywords": [
    "chat",
    "wechat"
  ],
  "author": "Zephyr Lu",
  "license": "GPL-3.0-or-later",
  "dependencies": {
    "brolog": "^1.8.3",
    "express": "^4.16.4",
    "file-box": "^0.8.27",
    "memory-card": "^0.6.13",
    "ts-node": "^8.0.2",
    "typescript": "^3.3.3",
    "wechaty": "^0.22.6",
    "wechaty-puppet": "^0.15.6",
    "wechaty-puppet-padchat": "^0.18.2",
    "wechaty-puppet-padpro": "0.0.45",
    "ws": "^6.1.3"
  }
}
`

**Comment by windmemory** [comment]
Please provide initialize code for the bot.

**Comment by Suley** [comment]
> Please provide initialize code for the bot.

Exactly same with your example code.

`
import { Wechaty } from 'wechaty'

const WECHATY_PUPPET_PADPRO_TOKEN = '#######'

const puppet = 'wechaty-puppet-padpro' // 使用ipad 的方式接入。

const puppetOptions = {
  token: WECHATY_PUPPET_PADPRO_TOKEN,
}

const bot = new Wechaty({
  puppet,
  puppetOptions,
})

// 设置完成

// 运行 wechaty
bot
.on('scan', (qrcode, status) => console.log(`Scan QR Code to login: ${status}\nhttps://api.qrserver.com/v1/create-qr-code/?data=${encodeURIComponent(qrcode)}`))
.on('login',            user => console.log(`User ${user} logined`))
.on('message',       message => console.log(`Message: ${message}`))
.start()

`

**Comment by kis87988** [comment]
Please check wechaty and propad version too

**Comment by windmemory** [comment]
Please remove `node_modules` folder and `package-lock.json`, then install wechaty with command `npm install wechaty@next`

After that, use the code below to try to start the bot

```ts
import { Wechaty } from 'wechaty'
import { PuppetPadpro } from 'wechaty-puppet-padpro'

const WECHATY_PUPPET_PADPRO_TOKEN = '#######'

const puppet = new PuppetPadpro({
  token: WECHATY_PUPPET_PADPRO_TOKEN,
})

const bot = new Wechaty({
puppet,
})

// 设置完成

// 运行 wechaty
bot
.on('scan', (qrcode, status) => console.log(`Scan QR Code to login: ${status}\nhttps://api.qrserver.com/v1/create-qr-code/?data=${encodeURIComponent(qrcode)}`))
.on('login', user => console.log(`User ${user} logined`))
.on('message', message => console.log(`Message: ${message}`))
.start()
```

**Comment by windmemory** [comment]
@Suley @usersuccess  Do you still seeing this issue?  If not, I will close this issue.
