### ISSUE TITLE
some message send out but serious delays

### ISSUE THREAD

**Issue by kis87988** [botorange/wechaty-puppet-padpro#50]
> 重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

## 0. 发 Issue 指南

- [x] 1. 请运行下面的命令，看问题是否可以被解决：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

- [x] 2. 请在 [FAQ 清单](https://docs.chatie.io/v/zh/faq) 看是否已有解决办法。

- [x] 3. 请先在issue 中搜关键信息，确认你要发的内容和之前的issue 不重复。

## 1. 提供你的包版本信息
- wechaty 版本：0.23.39
- wechaty-puppet-padpro 版本：0.0.41
- node 版本： (运行 `node --version` 获取版本) wehcaty docker version(v10)
- 你使用的操作系统：wechaty docker (ubuntu)

## 2. Bug 描述
the message eventrully being sent. However, it may be later than 3 minutes. 

## 3. 复现的步骤 (或者解决的步骤)
missing for now. reproduce later log with detail when I catch it on log

## 4. 期待程序运行的结果
the message should re-send ASAP when re-connect to server

## 5. 程序实际运行的结果
Delay a long time.

## 6. 完整的日志信息：
Missing.

## 7. 其他信息
I think it may be when the bot want to send message but the connection is missing.
and the message go to re-send queue, but stay in re-send queue too long
[bug]

**Comment by windmemory** [comment]
Let's wait until you got the reproduce steps

**Comment by windmemory** [comment]
Are you seeing this issue recently still?

**Comment by kis87988** [comment]
still testing, but the delay time is shorter than before.

**Comment by windmemory** [comment]
Cool, so let's close this and if the delay happened again, reopen it.
