### ISSUE TITLE
Friendship.Type.Confirm not show(not happen)

### ISSUE THREAD

**Issue by kis87988** [botorange/wechaty-puppet-padpro#51]
## 0. 发 Issue 指南

- [x] 1. 请运行下面的命令，看问题是否可以被解决：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

- [x] 2. 请在 [FAQ 清单](https://docs.chatie.io/v/zh/faq) 看是否已有解决办法。

- [x] 3. 请先在issue 中搜关键信息，确认你要发的内容和之前的issue 不重复。

## 1. 提供你的包版本信息
- wechaty 版本：0.23.39
- wechaty-puppet-padpro 版本：0.0.41
- node 版本： (运行 `node --version` 获取版本) docker version (v.10)
- 你使用的操作系统：docker system(ubuntu)

## 2. Bug 描述
Friendship.Type.Confirm not happen

## 3. 复现的步骤 (或者解决的步骤)
```ts
 .on('friendship', async friendship =>
  {
    let logMsg
    try
    {
      switch (friendship.type())
      {
        // 1. New Friend Request
        case Friendship.Type.Receive:
          logMsg = `received \`friendship\` event from ${friendship.contact().name()} with ${friendship.hello()}`
          logger.info(logMsg)
          await sleep(get_random_int_inclusive(10000, 30000))
          await friendship.accept()
          break

        // 2. Friend Ship Confirmed
        case Friendship.Type.Confirm: //never happen
          logMsg = 'friend ship confirmed with ' + friendship.contact().name()
          logger.info(logMsg)
          await sleep(get_random_int_inclusive(5000, 15000))
          await friendship.contact().say('Hi')
          await sleep(10000)
          await friendship.contact().sync()
          break
      }
      log.verbose('Bot', logMsg)
    }
    catch (e)
    {
      log.error('Bot', 'friendship event exception: %s', e.stack)
    }
  })
```
## 4. 期待程序运行的结果
Friend Ship Confirmed status should happen at some point of time

## 5. 程序实际运行的结果
Friend Ship Confirmed status not happen all the time

## 6. 完整的日志信息：
I am sorry, I can not copy paste due to special char.
<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js
```
[20190129_11.log](https://github.com/botorange/wechaty-puppet-padpro/files/2811840/20190129_11.log)
</details>

## 7. 其他信息

[bug]

**Comment by windmemory** [comment]
Who is the one that initialize the friendship? The bot or the other person?

Could you please test it with both ways?

**Comment by windmemory** [comment]
I saw this issue happened and continuing happened. This is caused by the change that WeChat made recently. Notice that before, when a new friend is added, there will be a line of word saying something like
```
You have added 【someone】 as your WeChat contact. Start chatting!
```
But now, this message won't be pushed, so there is no way for wechaty to catch this info anymore. 

The workaround for this issue is to monitor the `friendship.accept()` function call, when it succeed, do the logic that you usually do in the `Friendship.confim` event.

Sorry about this change, but wechaty can do nothing related to this issue.
