### ISSUE TITLE
获取群成员信息

### ISSUE THREAD

**Issue by jungle1307** [botorange/wechaty-puppet-padpro#57]
> 重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

**描述这个功能的缺失带来的问题**
 我们这边是一个比较大的企业，也有自己的内部微信群，考虑到经常有人员的入职和离职，所以需要对微信群里面的成员进行管理。管理包括：（1）甄别现有成员是公司员工；（2）近期已离职的员工，管理员每周定期清楚掉这些人。
    现在的问题是，通过微信网页协议获取到的wxid是加密后的，每次进去都会变化，所以 我们这边需要获取群成员真实的wxid列表，下次获取群列表，同一个人他的wxid是一样的。

   所以，贵公司那边有没有获取群成员真实wxid的技术方案或现有产品，考虑到对接微信的复杂度，我们这边更倾向于直接采购外部产品直接满足现有业务需求。请帮忙回复下！
    若贵公司有这类方案，请及时和我联系，看看能不提供API出来，我们这边完成后续 群成员认证的开发和对接。

**描述你期待的解决方案**

**描述你考虑过的备选方案**

**其他信息**
和此新功能相关的其他描述或截图。

[enhancement]

**Comment by windmemory** [comment]
Please refer to: https://docs.chatie.io/v/zh/puppet
