### ISSUE TITLE
TypeError: Cannot read property 'appmsg' of undefined

### ISSUE THREAD

**Issue by linglian** [botorange/wechaty-puppet-padpro#58]
> 重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

## 0. 发 Issue 指南

1. 请运行下面的命令，看问题是否可以被解决：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. 请在 [FAQ 清单](https://docs.chatie.io/v/zh/faq) 看是否已有解决办法。

3. 请先在issue 中搜关键信息，确认你要发的内容和之前的issue 不重复。

## 1. 提供你的包版本信息
- wechaty 版本：最新
- wechaty-puppet-padpro 版本：最新
- node 版本： (运行 `node --version` 获取版本) 10.9.0
- 你使用的操作系统：ubuntu16.04

## 2. Bug 描述
请用精简的语言描述你遇到的bug
16:52:50 INFO Wechaty <Puppet#0<PuppetPadpro>()/PuppetPadpro#0> start() v0.22.6 is starting...
16:52:50 INFO WechatGateway init(xxxxxxxxxxxxxxxxxxxxx, padpro.botorange.com:6666, undefined)
16:52:50 INFO WechatGateway initLongSocket() connected to wechat long host server: long.weixin.qq.com.
16:52:50 INFO WechatGateway initLongSocket() connected to wechat long host server: xxx.xxx.xxx.xxx.
16:52:51 INFO CacheManager init()
Contact<XXXXX> login
TypeError: Cannot read property 'appmsg' of undefined
    at Object.<anonymous> (/root/wechat/node_modules/wechaty-puppet-padpro/dist/src/pure-function-helpers/message-app-payload-parser.js:22:78)
    at Generator.next (<anonymous>)

一般在刚运行(扫码登录后)的时候会出现，可能是在创建登录信息缓存文件的时候的错误吧。

## 3. 复现的步骤 (或者解决的步骤)

**这一部分非常重要，如果你无法给出复现步骤，我们也很难提供相应的解决办法：**
例子:
- 第一步：扫码登录
- 第二步：然后会出现，不影响接下来的任何操作
- 。。。

## 4. 期待程序运行的结果
请用精简的语言描述你期待运行的结果

## 5. 程序实际运行的结果
请用精简的语言或者截图描述实际运行的结果（**请不要在这里粘贴日志截图**）

## 6. 完整的日志信息：
通过`WECHATY_LOG=silly`设定环境变量，将设置log 等级为 silly，获取最详细的日志信息（默认log 等级为 info）
**请提供完整的日志信息(不要只提供部分的日志截图，请复制粘贴日志内容！)**
<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js
复现不了了，下次遇到再补充。
```

</details>

## 7. 其他信息
有相关bug 的背景信息，可以在这里说明

[bug]

**Comment by windmemory** [comment]
这个log是需要bot接收某些特定格式的消息才会出现吧，而且应该是某些类型消息一定会触发这个问题，麻烦再列一下具体的消息类型

**Comment by windmemory** [comment]
This should be fixed with 0.0.51, please update your padpro version and observe whether this issue still happens.

**Comment by windmemory** [comment]
Close this issue since no response in two days. Please reopen if you see this again.
