### ISSUE TITLE
接收和發送消息

### ISSUE THREAD

**Issue by usersuccess** [botorange/wechaty-puppet-padpro#59]
🚨 这个issue 不是用来提问的 🚨

如果你有问题，请去这里提问： https://stackoverflow.com/questions/tagged/wechaty

[question]
接受羣消息有時候會出現如下錯誤：11:19:10 WARN PuppetPadpro messageFile(1078064955)
按照備註名稱發私信消息時，也會存在個別人發送消息失敗的情況

**Comment by usersuccess** [comment]
接收消息报错可能是因为不支持其他文件格式把。

**Comment by windmemory** [comment]
请按照issue模板填写，否则我们无法处理你的issue
