### ISSUE TITLE
Wechaty对象在调用stop方法以后，一直触发scan事件

### ISSUE THREAD

**Issue by zhengzhejun** [botorange/wechaty-puppet-padpro#60]
> 重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

## 0. 发 Issue 指南

1. 请运行下面的命令，看问题是否可以被解决：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. 请在 [FAQ 清单](https://docs.chatie.io/v/zh/faq) 看是否已有解决办法。

3. 请先在issue 中搜关键信息，确认你要发的内容和之前的issue 不重复。

## 1. 提供你的包版本信息
- wechaty 版本：wechaty@0.22.6
- wechaty-puppet-padpro 版本：wechaty-puppet-padpro@0.0.41
- node 版本： (运行 `node --version` 获取版本) v11.8.0
- 你使用的操作系统: os x

## 2. Bug 描述
请用精简的语言描述你遇到的bug
在logout回调函数中调用bot.stop()，bot停止失败，并持续触发scan事件。

## 3. 复现的步骤 (或者解决的步骤)
代码如下：
const bot = new Wechaty({
    puppet,
    puppetOptions,
})
bot.on('logout', onLogout)
    .on('login', onLogin)
    .on('scan', onScan)
    .on('error', onError)
    .on('message', onMessage)
function onLogout(user) {
    console.log(`${user.name()} logouted`)
    bot.stop()
}
function onScan(qrcode, status) {
    const qrcodeImageUrl = [
        'https://api.qrserver.com/v1/create-qr-code/?data=',
        encodeURIComponent(qrcode),
    ].join('')
    console.log(`[${status}] ${qrcodeImageUrl}\nScan QR Code above to log in: `)
    qrTerm.generate(qrcode, { small: false })

}

**这一部分非常重要，如果你无法给出复现步骤，我们也很难提供相应的解决办法：**
例子:
- 第一步：
- 第二步：
- 。。。

## 4. 期待程序运行的结果
bot.stop() 调用之后，接下来，该bot不应该响应其他的事件

## 5. 程序实际运行的结果
实际情况是，bot.stop()之后，一直会响应scan事件

## 6. 完整的日志信息：
通过`WECHATY_LOG=silly`设定环境变量，将设置log 等级为 silly，获取最详细的日志信息（默认log 等级为 info）
**请提供完整的日志信息(不要只提供部分的日志截图，请复制粘贴日志内容！)**
<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

```

</details>

## 7. 其他信息
有相关bug 的背景信息，可以在这里说明

[bug]

**Comment by windmemory** [comment]
I am working on fix this issue, will push out new version soon.

**Comment by windmemory** [comment]
Just updated `v0.0.59`, please try with that version.

**Comment by windmemory** [comment]
Close this issue since no more comments in last 18 days.
