### ISSUE TITLE
room.from().weixin() 获取到的微信号几乎都为null，一两个是有

### ISSUE THREAD

**Issue by chelsh** [botorange/wechaty-puppet-padpro#70]
## 1. 提供你的包版本信息
- wechaty 版本：0.22.6
- wechaty-puppet-padpro 版本：0.0.47
- node 版本： (运行 `node --version` 获取版本) 10.15.1
- 你使用的操作系统：mac

## 2. Bug 描述
群里面：room.from().weixin() 获取到的微信号几乎都为null，一两个是有。
20|wechat- | wechatNo:
20|wechat- | null
20|wechat- | Message#Text(👥Room<Wechaty Developers' Home 3>🗣Contact<桔小秘>👤Contact<管理员01>)<@Yiming Welcome to join us!
20|wechat- | 
20|wechat- | You’re invited into the 3rd group of Wech>
20|wechat- | from.cid:
20|wechat- | wxid_3xl8j2suau8b22
20|wechat- | wechatNo:
20|wechat- | orangiiss
20|wechat- | topic:
20|wechat- | Wechaty Developers' Home 3
20|wechat- | Message#Text(👥Room<wechaty-puppet-padchat 客户群>🗣Contact<高永好>👤Contact<管理员01>)<padpro里面出现一个问题>
20|wechat- | from.cid:
20|wechat- | ainever
20|wechat- | wechatNo:
20|wechat- | null
20|wechat- | topic:
20|wechat- | wechaty-puppet-padchat 客户群
20|wechat- | Message#Image(👥Room<wechaty-puppet-padchat 客户群>🗣Contact<高永好>👤Contact<管理员01>)
20|wechat- | from.cid:
20|wechat- | ainever
20|wechat- | wechatNo:
20|wechat- | null
20|wechat- | topic:
20|wechat- | wechaty-puppet-padchat 客户群
20|wechat- | Message#Image(👥Room<wechaty-puppet-padchat 客户群>🗣Contact<高永好>👤Contact<管理员01>)
20|wechat- | from.cid:
20|wechat- | ainever
20|wechat- | wechatNo:
20|wechat- | null
20|wechat- | topic:
20|wechat- | wechaty-puppet-padchat 客户群
20|wechat- | Message#Text(👥Room<wechaty-puppet-padchat 客户群>🗣Contact<高永好>👤Contact<管理员01>)<请问这是什么原因呢>
20|wechat- | from.cid:
20|wechat- | ainever
20|wechat- | wechatNo:
20|wechat- | null
20|wechat- | topic:
20|wechat- | wechaty-puppet-padchat 客户群
20|wechat- | Message#Text(👥Room<wechaty-puppet-padchat 客户群>🗣Contact<高原ོ>👤Contact<管理员01>)<没有找到这个contact>
20|wechat- | from.cid:
20|wechat- | lylezhuifeng
20|wechat- | wechatNo:
20|wechat- | null
20|wechat- | topic:
20|wechat- | wechaty-puppet-padchat 客户群
20|wechat- | Message#Text(👥Room<wechaty-puppet-padchat 客户群>🗣Contact<高原ོ>👤Contact<管理员01>)<而且find是一个异步的函数，需要用await>
20|wechat- | from.cid:
20|wechat- | lylezhuifeng
20|wechat- | wechatNo:
20|wechat- | null
20|wechat- | topic:
20|wechat- | wechaty-puppet-padchat 客户群
20|wechat- | Message#Text(👥Room<wechaty-puppet-padchat 客户群>🗣Contact<高原ོ>👤Contact<管理员01>)<请多参考文档哈>
20|wechat- | from.cid:
20|wechat- | lylezhuifeng
20|wechat- | wechatNo:
20|wechat- | null
20|wechat- | topic:
20|wechat- | wechaty-puppet-padchat 客户群

## 3. 复现的步骤 (或者解决的步骤)

**这一部分非常重要，如果你无法给出复现步骤，我们也很难提供相应的解决办法：**
例子:
- 第一步：
- 第二步：
- 。。。

## 4. 期待程序运行的结果
请用精简的语言描述你期待运行的结果

## 5. 程序实际运行的结果
请用精简的语言或者截图描述实际运行的结果（**请不要在这里粘贴日志截图**）

## 6. 完整的日志信息：
通过`WECHATY_LOG=silly`设定环境变量，将设置log 等级为 silly，获取最详细的日志信息（默认log 等级为 info）
**请提供完整的日志信息(不要只提供部分的日志截图，请复制粘贴日志内容！)**
<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

```

</details>

## 7. 其他信息
有相关bug 的背景信息，可以在这里说明

[bug]

**Comment by windmemory** [comment]
目前padpro只能拿到好友的微信号，除此之外都拿不到的

**Comment by chelsh** [comment]
> 目前padpro只能拿到好友的微信号，除此之外都拿不到的

那什么时候要支持：群里面的非好友的微信号也可以拿到呢？ 其他sdk比如wechaty-puppet-padchat可以拿到群里面的所有人微信号吗？

**Comment by windmemory** [comment]
目前还没有支持这个功能的计划，非好友的微信号有id可以用，但是没有weixin字段。
其他的也都拿不到
