### ISSUE TITLE
centos环境下安装失败

### ISSUE THREAD

**Issue by TinkerYin** [botorange/wechaty-puppet-padpro#74]
> 重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

## 0. 发 Issue 指南

1. 请运行下面的命令，看问题是否可以被解决：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. 请在 [FAQ 清单](https://docs.chatie.io/v/zh/faq) 看是否已有解决办法。

3. 请先在issue 中搜关键信息，确认你要发的内容和之前的issue 不重复。

## 1. 提供你的包版本信息
- wechaty 版本：0.22.6
- wechaty-puppet-padpro 版本：0.0.50
- node 版本：v10.15.2 (运行 `node --version` 获取版本)
- 你使用的操作系统：centos6.6

## 2. Bug 描述
请用精简的语言描述你遇到的bug

安装wechaty-puppet-padpro失败，卡在安装grpc这一步
```
6443 warn wechaty_padpro@1.0.0 No description
6444 warn wechaty_padpro@1.0.0 No repository field.
6445 verbose stack Error: ENOENT: no such file or directory, open '/home/xxx/www/wechaty_padpro/node_modules/grpc/node_modules/mkdirp/node_modules/minimist/package.json.2345449937'
6446 verbose cwd /home/xxx/www/wechaty_padpro
6447 verbose Linux 2.6.32-504.el6.x86_64
6448 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "wechaty-puppet-padpro"
6449 verbose node v10.15.2
6450 verbose npm  v6.4.1
6451 error path /home/xxx/www/wechaty_padpro/node_modules/grpc/node_modules/mkdirp/node_modules/minimist/package.json.2345449937
6452 error code ENOENT
6453 error errno -2
6454 error syscall open
6455 error enoent ENOENT: no such file or directory, open '/home/xxx/www/wechaty_padpro/node_modules/grpc/node_modules/mkdirp/node_modules/minimist/package.json.2345449937'
6456 error enoent This is related to npm not being able to find a file.
6457 verbose exit [ -2, true ]
```

## 3. 复现的步骤 (或者解决的步骤)
**这一部分非常重要，如果你无法给出复现步骤，我们也很难提供相应的解决办法：**

复现步骤中一定要给出*复现代码*

例子:
- 第一步：
- 第二步：
- 。。。

```
npm install wechaty-puppet-padpro
```

## 4. 期待程序运行的结果
请用精简的语言描述你期待运行的结果

## 5. 程序实际运行的结果
请用精简的语言或者截图描述实际运行的结果（**请不要在这里粘贴日志截图**）

## 6. 完整的日志信息：
通过`WECHATY_LOG=silly`设定环境变量，将设置log 等级为 silly，获取最详细的日志信息（默认log 等级为 info）
**请提供完整的日志信息(不要只提供部分的日志截图，请复制粘贴日志内容！)**
<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

```

</details>

## 7. 其他信息
有相关bug 的背景信息，可以在这里说明

参考这个文章，已经升级gcc4.8，glibc2.17
https://www.luyouli.com/?p=52

[bug]

**Comment by windmemory** [comment]
`'/home/xxx/www/wechaty_padpro/node_modules/grpc/node_modules/mkdirp/node_modules/minimist/package.json.2345449937'`

这个路径的文件存在么？

**Comment by TinkerYin** [comment]
不存在，看起来像minimist这个包安装失败，但是单独装又没有问题

**Comment by windmemory** [comment]
无法复现这个问题，我在centos6.6系统里面成功安装了wechaty-puppet-padpro v0.0.58版本

![image](https://user-images.githubusercontent.com/6801292/57445946-0feec080-7286-11e9-84d7-0909d12b2522.png)

这个问题和wechaty-puppet-padpro无关，所以请自行检查原因

中途安装了出现了一个报错
```shell
prebuild-install WARN install No prebuilt binaries found (target=10.15.3 runtime=node arch=x64 platform=linux)
make: Entering directory `/root/test/node_modules/nosql-leveldb/build'
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/builder.o
cc1plus: error: unrecognized command line option "-std=gnu++1y"
make: *** [Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/builder.o] Error 1
make: Leaving directory `/root/test/node_modules/nosql-leveldb/build'
```
之后参考下面的文章解决
https://blog.csdn.net/qq_26744901/article/details/82504079

除此之外，安装过程没出现其他的问题

我用的centOS是aws的镜像 CentOS Linux release 6.6(hvm-import) test only

这个issue关闭了
