### ISSUE TITLE
Message.forward() is not fully working

### ISSUE THREAD

**Issue by lhr0909** [botorange/wechaty-puppet-padpro#76]
> 重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

## 0. 发 Issue 指南

1. 请运行下面的命令，看问题是否可以被解决：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. 请在 [FAQ 清单](https://docs.chatie.io/v/zh/faq) 看是否已有解决办法。

3. 请先在issue 中搜关键信息，确认你要发的内容和之前的issue 不重复。

## 1. 提供你的包版本信息
- wechaty 版本：v0.22.6
- wechaty-puppet-padpro 版本：v0.0.48
- node 版本： (运行 `node --version` 获取版本) v10.12.0
- 你使用的操作系统：MacOS 10.14.3

## 2. Bug 描述
请用精简的语言描述你遇到的bug

通过 `Message.forward()` 转发消息 有部分类型无法成功转发

- 自定义表情
- 小程序
- 链接（缩略图无法正常显示）

## 3. 复现的步骤 (或者解决的步骤)

**这一部分非常重要，如果你无法给出复现步骤，我们也很难提供相应的解决办法：**

复现步骤中一定要给出*复现代码*

我们把一个chatRoom的Message提取出来 然后转发到另外一个chatRoom时出现问题：

```javascript
bot.on('message', async (message) => {
  debug(message);
  pubsub.publish('incomingMsg', {
    incomingMsg: {
      contact: message.from().id,
      content: message.text(),
    },
  });
  const clients = await prisma.clients();
  clients.forEach((client) => {
    if (client.externalWechatRoomId === message.room().id) {
      // forward to internal
      const internalRoom = bot.Room.load(client.internalWechatRoomId);
      message.forward(internalRoom);
    }
  });
});
```

## 4. 期待程序运行的结果
请用精简的语言描述你期待运行的结果

消息应该能够原封不动地转发成功 无论何种格式

## 5. 程序实际运行的结果
请用精简的语言或者截图描述实际运行的结果（**请不要在这里粘贴日志截图**）

![wechatimg37](https://user-images.githubusercontent.com/1154575/53806323-9a196080-3f87-11e9-8276-4fe027f0331e.png)
![wechatimg36](https://user-images.githubusercontent.com/1154575/53806322-9980ca00-3f87-11e9-92c5-d21a7548bd6e.png)

## 6. 完整的日志信息：
通过`WECHATY_LOG=silly`设定环境变量，将设置log 等级为 silly，获取最详细的日志信息（默认log 等级为 info）
**请提供完整的日志信息(不要只提供部分的日志截图，请复制粘贴日志内容！)**
<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

```

</details>

## 7. 其他信息
有相关bug 的背景信息，可以在这里说明

[bug]

**Comment by lhr0909** [comment]
Happy to work on a fix that is based on this proposal: https://github.com/Chatie/wechaty/issues/1678 I believe if we send the same raw message payload from one room to another, it should work and wechat should gracefully handle cases like that.

**Comment by windmemory** [comment]
Yep, you are right, raw messages should fix this issue. 

Looking forward for your PR :P
