### ISSUE TITLE
图片消息获取图片内容 间歇性失败

### ISSUE THREAD

**Issue by oday0311** [botorange/wechaty-puppet-padpro#83]
> 重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

## 0. 发 Issue 指南

1. 请运行下面的命令，看问题是否可以被解决：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```
否

2. 请在 [FAQ 清单](https://docs.chatie.io/v/zh/faq) 看是否已有解决办法。

无
3. 请先在issue 中搜关键信息，确认你要发的内容和之前的issue 不重复。

## 1. 提供你的包版本信息
- wechaty 版本： "wechaty": "^0.22.6",
- wechaty-puppet-padpro 版本： "wechaty-puppet-padpro": "0.0.52",
- node 版本： (运行 `node --version` 获取版本) v11.10.1
- 你使用的操作系统： mac or centos.

## 2. Bug 描述
请用精简的语言描述你遇到的bug

接收图片消息后， 尝试获取图片内容， 有的时候可以拿到图片， 有的时候拿不到图片， 
var file = await msg.toFileBox()
 var buffer = await file.toBuffer() 无法完成执行

## 3. 复现的步骤 (或者解决的步骤)

**这一部分非常重要，如果你无法给出复现步骤，我们也很难提供相应的解决办法：**

复现步骤中一定要给出*复现代码*

例子:
case bot.Message.Type.Image:
          logger.info(" before  image check .. " 
                var file = await msg.toFileBox()
                var buffer = await file.toBuffer()
          logger.info(" after  image check .. " 

## 4. 期待程序运行的结果
请用精简的语言描述你期待运行的结果
before image check
after image check

## 5. 程序实际运行的结果
请用精简的语言或者截图描述实际运行的结果（**请不要在这里粘贴日志截图**）
有的时候可以完成执行
before image check
after image check

有的时候， 
只有before image check

## 6. 完整的日志信息：
通过`WECHATY_LOG=silly`设定环境变量，将设置log 等级为 silly，获取最详细的日志信息（默认log 等级为 info）
**请提供完整的日志信息(不要只提供部分的日志截图，请复制粘贴日志内容！)**
<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

```

</details>
===============下面是无法接收图片的情况下的日志---------------

[error.txt](https://github.com/botorange/wechaty-puppet-padpro/files/2969358/error.txt)

===============下面是正常接收图片的日志----------------------

edupeApi dedupe() no need to dedupe api GrpcGetMsgImage.
11:36:23 SILL WechatGateway sendLong() reqSeq: 1238585010
11:36:23 SILL WechatGateway sendLong() receive back package size: 55143
11:36:24 SILL GrpcGateway parse(GrpcGetMsgImage) get response: {"imageData":"/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgFBgcGBQgHBgcJCAgJDBMMDAsLDBgREg4THBgdHRsYGxofIywlHyEqIRobJjQnKi4vMTIxHiU2OjYwOiwwMTD/2wBDAQgJCQwKDBcMDBcwIBsgMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMD
11:36:24 SILL DedupeApi dedupe() no need to dedupe api GrpcGetMsgImage.
11:36:24 SILL WechatGateway sendLong() reqSeq: 3028107212
11:36:24 SILL WechatGateway sendLong() receive back package size: 517
11:36:24 SILL GrpcGateway parse(GrpcGetMsgImage) get response: {"imageData":"ACg9KKKAOL8deD4NetzLCBHeIP3b44J/un2/l1+vi15aT2Fy1vcxmKWM4YHHUfQnj0PevpyuN8Z+DIfECGRG+z3aDCzAZ4PUHkZHp6Hn1BxqU1LU9zLM0lhpck/hPGtK0+61W6W3tI97k88kgDqScnoK9r8HeFLXQbNV/wBZM2C7ngsecfh7VJ4V8K
wx_image/2019/3/15/1552620984482.jpg
## 7. 其他信息
有相关bug 的背景信息，可以在这里说明

[bug]

**Comment by windmemory** [comment]
请提供发送的图片，以及发送图片的时候用的客户端（mac，ios，android，pc，ipad）

**Comment by windmemory** [comment]
@oday0311 你好，请提供一下发送的图片，以及发送图片使用的客户端

**Comment by oday0311** [comment]
发送图片用的是ios手机， 选用的图片应该不太影响结果， 我们测试的时候用了不同的图片， 都会偶尔出现这个情况， 复现概率还是不小的，
