### ISSUE TITLE
每次重启后，on('message')都会触发最近的旧消息

### ISSUE THREAD

**Issue by chenyuantao** [botorange/wechaty-puppet-padpro#85]
期望是不会触发最近的旧消息，只接受启动后的新消息

**Comment by chenyuantao** [comment]
而且Message对象也没有返回server_id来标识消息的唯一性，所以也没办法判断是否同一条消息被触发了两次

**Comment by lhr0909** [comment]
`messageId` 应该会是相同的 所以可以考虑用 `messageId` 去重

**Comment by chenyuantao** [comment]
> `messageId` 应该会是相同的 所以可以考虑用 `messageId` 去重

Property 'messageId' does not exist on type 'Message'.ts(2339)

**Comment by windmemory** [comment]
It should be `message.id` to retrieve it.
