### ISSUE TITLE
发消息报错退出

### ISSUE THREAD

**Issue by 763147503** [botorange/wechaty-puppet-padpro#90]
> 重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

## 0. 发 Issue 指南

1. 请运行下面的命令，看问题是否可以被解决：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. 请在 [FAQ 清单](https://docs.chatie.io/v/zh/faq) 看是否已有解决办法。

3. 请先在issue 中搜关键信息，确认你要发的内容和之前的issue 不重复。

## 1. 提供你的包版本信息
- wechaty 版本：^0.23.40
- wechaty-puppet-padpro 版本：0.0.52
- node 版本： (运行 `node --version` 获取版本) v10.15.0
- 你使用的操作系统：centos

## 2. Bug 描述
请用精简的语言描述你遇到的bug
登录后正常发送消息几分钟报错，用户退出。

## 3. 复现的步骤 (或者解决的步骤)

**这一部分非常重要，如果你无法给出复现步骤，我们也很难提供相应的解决办法：**

复现步骤中一定要给出*复现代码*

例子:
- 第一步：重新登录
- 第二步：接受发送消息
代码：if (send_type == "pic") {
              try{
                const fileBox2 = FileBox.fromFile(content);
                await contact.say(fileBox2);
              }catch (e){
                console.log('message say fail')
              }
              console.log("图文");
            } else if (send_type == "text") {
              try{
                await contact.say(content);
              }catch (e){
                console.log('message say fail')
              }
              console.log("文字");
            }

- 。。。

## 4. 期待程序运行的结果
正常发送消息
请用精简的语言描述你期待运行的结果

## 5. 程序实际运行的结果
14:55:36 INFO PadproManager Connection has problem, reset self to recover the connection.
14:55:36 WARN PuppetPadpro startManager() manager.on(reset) for undefined. Restarting PuppetPadpro ... 
Contact<> logout
14:55:36 INFO Wechaty <Puppet#0<PuppetPadpro>()/PuppetPadpro#0> stop() v0.23.40 is stoping ...
14:55:36 WARN PuppetPadpro stop() is called on a OFF puppet. await ready(off) and return.
14:55:36 INFO CacheManager release()
14:55:36 WARN PadproManager releaseQueue() subscriptions have been released.
14:55:36 WARN PadproManager releaseQueue() queues have been released.
14:55:36 INFO CacheManager release()
14:55:36 WARN CacheManager init() CacheManager not exist, no need to release it.
14:55:36 INFO WechatGateway stop()
14:55:36 INFO WechatGateway initLongSocket() connection to wechat long host server: long.weixin.qq.com ended.
14:55:36 INFO WechatGateway init(puppet_padpro_86fbdb0351048b66, padpro.botorange.com:6666, undefined)
14:55:36 INFO WechatGateway initLongSocket() connection to wechat long host server: long.weixin.qq.com closed.
14:55:37 INFO WechatGateway initLongSocket() connected to wechat long host server: long.weixin.qq.com.
请用精简的语言或者截图描述实际运行的结果（**请不要在这里粘贴日志截图**）

## 6. 完整的日志信息：
通过`WECHATY_LOG=silly`设定环境变量，将设置log 等级为 silly，获取最详细的日志信息（默认log 等级为 info）
**请提供完整的日志信息(不要只提供部分的日志截图，请复制粘贴日志内容！)**
<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

```

</details>

## 7. 其他信息
有相关bug 的背景信息，可以在这里说明

[bug]

**Comment by windmemory** [comment]
请提供完整日志信息

**Comment by windmemory** [comment]
Close this issue since no more information provided for last 18 days.
