### ISSUE TITLE
ready事件要等加载完所有群的群成员才执行吗？

### ISSUE THREAD

**Issue by guohui666** [botorange/wechaty-puppet-padpro#92]
ready事件要等加载完所有群的群成员才执行吗？太慢了😭

**Comment by windmemory** [comment]
是的，要等所有数据加载完毕才会执行

这个issue还有别的问题么？没有的话就关闭了

**Comment by guohui666** [comment]
PADPRO_REPLAY_MESSAGE=true node bot.js   按照这个格式运行不起来啊，还有啥特殊操作😭？

**Comment by windmemory** [comment]
没明白什么意思？有具体的运行代码和环境么？如果运行不起来，请按照issue模板新开另外一个issue

**Comment by windmemory** [comment]
这个issue先关闭了，如果有其他的问题，请麻烦开其他的issue来讨论
