### ISSUE TITLE
程序运行中抛出异常然后自动退出

### ISSUE THREAD

**Issue by samstar** [botorange/wechaty-puppet-padpro#93]
## 1. 提供你的包版本信息
- wechaty 版本： v0.22.6
- wechaty-puppet-padpro 版本：v0.0.47
- node 版本： v10.15.1
- 你使用的操作系统：Centos7.0

## 2. Bug 描述
间隔数日程序会自动退出，异常日志如下：
00:46:59 WARN PuppetPadpro startManager() manager.on(reset) for startCheckScan() checkScanLoop() exception. Restarting PuppetPadpro ... 
00:46:59 WARN PuppetPadpro logout() this.id not exist
00:46:59 WARN CacheManager init() CacheManager not exist, no need to release it.

**Comment by windmemory** [comment]
请按照issue模板填写，提供详细的异常日志，之后我们会尽快处理，谢谢

**Comment by windmemory** [comment]
Please try with `v0.0.59` and see if issue still happens.

**Comment by windmemory** [comment]
Close this issue for no more comments for last 18 days.
