### ISSUE TITLE
onScan事件不被触发，无法出现二维码，自动登录未知账号。

### ISSUE THREAD

**Issue by kangtk** [botorange/wechaty-puppet-padpro#95]
> 重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

## 0. 发 Issue 指南

1. 请运行下面的命令，看问题是否可以被解决：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. 请在 [FAQ 清单](https://docs.chatie.io/v/zh/faq) 看是否已有解决办法。

3. 请先在issue 中搜关键信息，确认你要发的内容和之前的issue 不重复。

## 1. 提供你的包版本信息
- wechaty 版本：
- wechaty-puppet-padpro 版本：
- node 版本： (运行 `node --version` 获取版本)
- 你使用的操作系统：

## 2. Bug 描述
请用精简的语言描述你遇到的bug

## 3. 复现的步骤 (或者解决的步骤)

**这一部分非常重要，如果你无法给出复现步骤，我们也很难提供相应的解决办法：**

复现步骤中一定要给出*复现代码*

例子:
- 第一步：
- 第二步：
- 。。。

## 4. 期待程序运行的结果
请用精简的语言描述你期待运行的结果

## 5. 程序实际运行的结果
请用精简的语言或者截图描述实际运行的结果（**请不要在这里粘贴日志截图**）

## 6. 完整的日志信息：
通过`WECHATY_LOG=silly`设定环境变量，将设置log 等级为 silly，获取最详细的日志信息（默认log 等级为 info）
**请提供完整的日志信息(不要只提供部分的日志截图，请复制粘贴日志内容！)**
<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

```

</details>

## 7. 其他信息
有相关bug 的背景信息，可以在这里说明

[bug]

**Comment by windmemory** [comment]
这个可能因为token绑定了其他的微信号，`bot.logout`之后就都正常了对吧

**Comment by kangtk** [comment]
对的，需要手工调用logout就可以了。

而且我发现，机器人是一直自动保持登录状态的，但是并没有在本地找到profile文件，这是保活在padpro服务器的吗？

发自我的 iPhone

**Comment by windmemory** [comment]
是的，登录数据目前是存在云端的

**Comment by kangtk** [comment]
那就是永不会自动掉线咯？

另外请教下，对微信来说这个iPad登录微信号的IP地址是哪个环节生成的？扫码时的客户端还是本地服务器还是padpro服务器？

发自我的 iPhone

**Comment by kangtk** [comment]
那如果需要在一台服务器上跑多个机器人的话，会很容易被微信封号吧？因为是同一个IP地址。
wechaty本地服务器有办法自己模拟多个IP地址吗？

发自我的 iPhone

**Comment by windmemory** [comment]
模拟IP的话，本身就不是应用层的话题了，wechaty是做不到的

同一个IP地址，目前还没看到微信用这个来封号。我们的理解是如果做了微信不喜欢的事情，比如传播黄赌毒，或者频繁的骚扰微信其他用户等等，微信可能会想办法来封号，如果做的是正常业务，微信不会根据同一个IP太多连接数来封号。

**Comment by kangtk** [comment]
好的，微信封号规则，我们再研究下。

这样的话，等于是微信服务器是直接跟wechaty本地服务器通讯的？只是传输的数据是由wechaty本地服务器提交给padpro协议服务器进行加解密再返回回来？

另外，从微信服务器同步过来的好友以及群数据，是缓存在wechaty本地服务器还是云端的padpro协议服务器？这会影响我们实现的时候要不要自己在做一层数据缓存了。

谢谢。

**Comment by windmemory** [comment]
> 这样的话，等于是微信服务器是直接跟wechaty本地服务器通讯的？只是传输的数据是由wechaty本地服务器提交给padpro协议服务器进行加解密再返回回来？

是的

> 另外，从微信服务器同步过来的好友以及群数据，是缓存在wechaty本地服务器还是云端的padpro协议服务器？这会影响我们实现的时候要不要自己在做一层数据缓存了。

本地服务器

**Comment by windmemory** [comment]
Close this issue since no active conversation during last 10 days.
